/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrator;

import Config.Global;
import Classes.Account;
import Classes.ChartsAnalysis;
import Classes.Constant;
import Classes.TotalRecords;
import Classes.User;
import DataAccess.DataAccess;
import Technician.FrmViewCustomer;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class AfrmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    public AfrmDashboard() {
        TotalRecords GetTotalRecords = new TotalRecords();
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();
        
        lblUserActivate.setText("" + GetTotalRecords.GetTotalActivate());
        lblCategory.setText("" + GetTotalRecords.GetTotalActivateCategory());
        lblProduct.setText("" + GetTotalRecords.GetTotalActivateProduct());
        lblTotalUser.setText("/" + GetTotalRecords.GetTotalUser());
        lblTotalCategory.setText("/" + GetTotalRecords.GetTotalCategory());
        lblTotalProduct.setText("/" + GetTotalRecords.GetTotalProduct());
        lblTotalAppointment.setText("/" + GetTotalRecords.GetTotalAppointment());
        lblTotalPending.setText(GetTotalRecords.GetTotalCompleteAppointment()+"");
        lblTotalCustomer.setText("/"+ GetTotalRecords.GetTotalCustomer());
        lblTotalCustomerWithoutAppointment.setText(GetTotalRecords.GetTotalCustomerWithoutPayment()+"");
        
        
        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.Dashboard);
        jLabel20.setText(Global.role);
        lblRole.setText(Global.name);
        
        ChartsAnalysis CA = new ChartsAnalysis();
        jPanel5.removeAll();
        jPanel5.add(CA.GetGenderPieCharts());
        getAppointment();
    }

    public void CurrentDateandTime(){
            Thread clock = new Thread() {
            public void run() {
                try {
                    for(;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " +day+"/"+(month+1)+"/"+year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: "+hour+":"+(minute)+":"+second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
            clock.start();
            
        }
    
    public void getAppointment()
    {
        DataAccess da = new DataAccess();
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
        try
        {
            da.setFileName("Appointment.txt");
            ArrayList<String> data = da.readAll();
            for(String rec: data) {
                String[] split = rec.split("\\|");
                if(split[9].equals("PENDING")){
                    jLabel12.setText("Appointment Details: ");
                    txtAppointmentNotification.setText(txtAppointmentNotification.getText() + "\n   Appointment Date and Time: " + split[6] + " from " + split[7] + " to " + split[8] + " with " + split[1]);
                    txtAppointmentNotification.setVisible(true);
                }
            }
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Can't load data from database");
        }
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAppointmentNotification = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblUserActivate = new javax.swing.JLabel();
        lblTotalUser = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblTotalCategory = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblTotalProduct = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalPending = new javax.swing.JLabel();
        lblTotalAppointment = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalCustomerWithoutAppointment = new javax.swing.JLabel();
        lblTotalCustomer = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 17);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 255, 0));
        lblRole.setText("jLabel2");
        jPanel1.add(lblRole);
        lblRole.setBounds(10, 40, 200, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Dashboard");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Customer");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 180, 130, 20);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 110, 250, 50);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage User");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 240, 100, 30);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Clean Database");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(80, 300, 110, 20);

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(140, 10, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 750);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("LOGOUT");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 10, 70, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.add(jPanel5);
        jPanel5.setBounds(50, 240, 360, 300);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 550, 770, 10);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("No Appointment !");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 560, 530, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 255));

        txtAppointmentNotification.setEditable(false);
        txtAppointmentNotification.setBackground(new java.awt.Color(255, 204, 255));
        txtAppointmentNotification.setColumns(20);
        txtAppointmentNotification.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAppointmentNotification.setForeground(new java.awt.Color(0, 0, 255));
        txtAppointmentNotification.setLineWrap(true);
        txtAppointmentNotification.setRows(10);
        jScrollPane1.setViewportView(txtAppointmentNotification);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 610, 730, 120);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel5.setText("Activate User");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(10, 10, 83, 16);

        lblUserActivate.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblUserActivate.setForeground(new java.awt.Color(0, 255, 0));
        lblUserActivate.setText("jLabel5");
        jPanel7.add(lblUserActivate);
        lblUserActivate.setBounds(130, 40, 90, 50);

        lblTotalUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalUser.setText("jLabel21");
        jPanel7.add(lblTotalUser);
        lblTotalUser.setBounds(153, 100, 60, 16);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(20, 110, 220, 120);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel6.setText("Activate Category");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(10, 10, 120, 16);

        lblCategory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(0, 255, 0));
        lblCategory.setText("jLabel5");
        jPanel8.add(lblCategory);
        lblCategory.setBounds(130, 40, 90, 50);

        lblTotalCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCategory.setText("jLabel21");
        jPanel8.add(lblTotalCategory);
        lblTotalCategory.setBounds(160, 100, 53, 16);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(260, 110, 220, 120);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel4.setText("Activate Product");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 16);

        lblProduct.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(0, 255, 0));
        lblProduct.setText("jLabel5");
        jPanel6.add(lblProduct);
        lblProduct.setBounds(130, 40, 90, 50);

        lblTotalProduct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalProduct.setText("jLabel21");
        jPanel6.add(lblTotalProduct);
        lblTotalProduct.setBounds(160, 100, 53, 16);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(500, 110, 220, 120);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jLabel13.setText("Pending Payment");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 10, 130, 16);

        lblTotalPending.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblTotalPending.setForeground(new java.awt.Color(0, 255, 0));
        lblTotalPending.setText("jLabel5");
        jPanel9.add(lblTotalPending);
        lblTotalPending.setBounds(130, 40, 90, 50);

        lblTotalAppointment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAppointment.setText("jLabel21");
        jPanel9.add(lblTotalAppointment);
        lblTotalAppointment.setBounds(153, 100, 60, 16);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(500, 390, 220, 120);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        jLabel15.setText("Appointment");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(10, 30, 120, 16);

        lblTotalCustomerWithoutAppointment.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblTotalCustomerWithoutAppointment.setForeground(new java.awt.Color(0, 255, 0));
        lblTotalCustomerWithoutAppointment.setText("jLabel5");
        jPanel10.add(lblTotalCustomerWithoutAppointment);
        lblTotalCustomerWithoutAppointment.setBounds(130, 40, 90, 50);

        lblTotalCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCustomer.setText("jLabel21");
        jPanel10.add(lblTotalCustomer);
        lblTotalCustomer.setBounds(160, 100, 53, 16);

        jLabel16.setText("Customer without");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(10, 10, 120, 16);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(500, 250, 220, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        FrmManageUser frmManageUser = new FrmManageUser();
        frmManageUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Account Logout", JOptionPane.YES_NO_OPTION);
            if(confirmed == JOptionPane.YES_OPTION)
            {
                Account account = new Account();
                account.logout(Global.user_login_id);
                frmLogin.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid logged out. Please launch the program from login page.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new FrmViewCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new FrmCleanDatabase().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfrmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTotalAppointment;
    private javax.swing.JLabel lblTotalCategory;
    private javax.swing.JLabel lblTotalCustomer;
    private javax.swing.JLabel lblTotalCustomerWithoutAppointment;
    private javax.swing.JLabel lblTotalPending;
    private javax.swing.JLabel lblTotalProduct;
    private javax.swing.JLabel lblTotalUser;
    private javax.swing.JLabel lblUserActivate;
    private javax.swing.JTextArea txtAppointmentNotification;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
