/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrator;

import Config.Global;
import Classes.Account;
import Classes.Constant;
import Classes.Validation;
import Classes.Initials;
import Classes.Manager;
import Classes.Technician;
import Classes.User;
import Technician.FrmViewCustomer;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class FrmAddUser extends javax.swing.JFrame {

    /**
     * Creates new form frmAddManager
     */
    public FrmAddUser() {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);

        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.AddNewManager);
        jLabel4.setText(con.Security);
        jLabel16.setText(con.Question);
        jLabel15.setText(con.Answer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        cmbQuestion = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jCalendarCombo1 = new org.gui.JCalendarCombo();
        txtRole = new javax.swing.JComboBox<>();
        chkPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        txtCPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 430, 400, 60);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("ACTIVE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(630, 120, 70, 17);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Username");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 160, 80, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Date of Birth");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 200, 90, 17);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Password");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 240, 150, 17);

        txtUserID.setEditable(false);
        txtUserID.setForeground(new java.awt.Color(153, 153, 153));
        txtUserID.setText("AUTO-GENRATED");
        jPanel2.add(txtUserID);
        txtUserID.setBounds(180, 110, 300, 40);

        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserIDFocusLost(evt);
            }
        });
        jPanel2.add(txtUsername);
        txtUsername.setBounds(180, 150, 300, 40);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Confirm Password");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 280, 150, 17);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 550, 150, 17);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 510, 150, 17);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("Role");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 320, 150, 17);
        jPanel2.add(txtAnswer);
        txtAnswer.setBounds(180, 540, 300, 40);

        cmbQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your eldest cousin's name?", "What is your youngest child's nickname?", "What is your favourite food name?", "Name of your favourite band or singer?", "What was the name of your first pet?", "What is your dream job?", "In what city did your parents meet?" }));
        jPanel2.add(cmbQuestion);
        cmbQuestion.setBounds(180, 510, 300, 27);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("User ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 120, 110, 17);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("Status");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(500, 120, 110, 17);

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreate);
        btnCreate.setBounds(640, 690, 120, 50);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("BACK");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(40, 10, 40, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(650, 10, 110, 40);
        jPanel2.add(jCalendarCombo1);
        jCalendarCombo1.setBounds(190, 200, 280, 26);

        txtRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TECHNICIAN", "MANAGER" }));
        jPanel2.add(txtRole);
        txtRole.setBounds(190, 320, 280, 27);

        chkPassword.setText("View Password");
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(chkPassword);
        chkPassword.setBounds(490, 240, 140, 23);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(180, 230, 300, 40);
        jPanel2.add(txtCPassword);
        txtCPassword.setBounds(180, 270, 300, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText().toLowerCase();
        String Username = txtUsername.getText().toUpperCase();
        String DOB = jCalendarCombo1.getSelectedDate();
        String Password = txtPassword.getText();
        String CPassword = txtCPassword.getText();
        String Role = txtRole.getSelectedItem().toString();
        String Question = cmbQuestion.getSelectedItem().toString();
        String Answer = txtAnswer.getText().toUpperCase();
        String Status = jLabel5.getText();
        ArrayList<String> UserDetails;
        UserDetails = new ArrayList<>();
        UserDetails.add(UserID);
        UserDetails.add(Username);
        UserDetails.add(DOB);
        UserDetails.add(Password);
        UserDetails.add(Role);
        UserDetails.add(Question);
        UserDetails.add(Answer);
        UserDetails.add(Status);

        Validation checkUser = new Validation();
        try {
            if (!UserID.isEmpty() && !Username.isEmpty() && !DOB.isEmpty() && !Password.isEmpty() && !CPassword.isEmpty() && !Answer.isEmpty()) {
                if (checkUser.checkUser(UserID)) {
                    if (checkUser.checkpassword(Password)) {
                        if (checkUser.checkDOB(DOB)) {
                            if (Password.compareTo(CPassword) == 0) {
                                if (Role.equals("MANAGER")) {
                                    User user = new Manager(UserDetails);
                                    user.Add();
                                    JOptionPane.showMessageDialog(rootPane, "One manager is added.", "User Added", JOptionPane.INFORMATION_MESSAGE);
                                    ClearFields();
                                    new FrmManageUser().setVisible(true);
                                    this.dispose();
                                } else {
                                    User userTechnician = new Technician(UserDetails);
                                    userTechnician.Add();
                                    JOptionPane.showMessageDialog(rootPane, "One technician is added.", "User Added", JOptionPane.INFORMATION_MESSAGE);
                                    ClearFields();
                                    new FrmManageUser().setVisible(true);
                                    this.dispose();
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "The password does not match", "Password Mismatch", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Please make sure that day before for date of birth");
                        }

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please provide a password with the length of 8 to 16.", "Password Error", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "The username has already existed in the system. Please use another name.", "Error Message", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please make sure that you have entered all the text fields.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Something happened. Please try to login again.", "Error Message", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    public void ClearFields() {
        txtUserID.setText("AUTO-GENERATED");
        txtUsername.setText("");
        txtPassword.setText("");
        txtCPassword.setText("");
        txtAnswer.setText("");
    }

    private void txtUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIDFocusLost
        // TODO add your handling code here:
        Initials getInitials = new Initials();
        try {
            txtUserID.setText(getInitials.GetInitials(txtUsername.getText()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtUserIDFocusLost

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        new AfrmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        // TODO add your handling code here:
        if (chkPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
            txtCPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
            txtCPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JComboBox<String> cmbQuestion;
    private org.gui.JCalendarCombo jCalendarCombo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JPasswordField txtCPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtRole;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
