/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrator;

import Config.Global;
import Classes.Account;
import Classes.Admin;
import Classes.Appointment;
import Classes.Category;
import Classes.Constant;
import Classes.Customer;
import Classes.Feedback;
import Classes.Payment;
import Classes.Product;
import Classes.User;
import Classes.Validation;
import Technician.FrmViewCustomer;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class FrmCleanDatabase extends javax.swing.JFrame {

    /**
     * Creates new form frmCleanDatabase
     */
    public FrmCleanDatabase() {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();

        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.CleanDatabase);

        jLabel22.setText(Global.role);
        lblRole.setText(Global.name);
    }

    public void CurrentDateandTime() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " + day + "/" + (month + 1) + "/" + year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: " + hour + ":" + (minute) + ":" + second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
        clock.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClean = new javax.swing.JButton();
        btnClean1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClean2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnClean3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 17);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 255, 0));
        lblRole.setText("jLabel2");
        jPanel1.add(lblRole);
        lblRole.setBounds(10, 40, 200, 40);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Clean Database");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21);
        jLabel21.setBounds(80, 16, 110, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 290, 250, 50);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Customer");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 180, 130, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage User");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 240, 100, 30);

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("jLabel20");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(140, 10, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 750);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("LOGOUT");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 10, 70, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Reset Database");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 330, 240, 20);

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);
        btnReset.setBounds(290, 320, 120, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Clear Category and Product");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 130, 200, 20);

        btnClean.setText("CLEAN");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel2.add(btnClean);
        btnClean.setBounds(290, 120, 120, 40);

        btnClean1.setText("CLEAN");
        btnClean1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClean1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClean1);
        btnClean1.setBounds(290, 170, 120, 40);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Clear Payment and Feedback");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 180, 200, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Clear Members and Appointment");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 230, 240, 20);

        btnClean2.setText("CLEAN");
        btnClean2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClean2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClean2);
        btnClean2.setBounds(290, 220, 120, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Clear System User");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 280, 240, 20);

        btnClean3.setText("CLEAN");
        btnClean3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClean3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClean3);
        btnClean3.setBounds(290, 270, 120, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new FrmViewCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Account Logout", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                Account account = new Account();
                account.logout(Global.user_login_id);
                frmLogin.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid logged out. Please launch the program from login page.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new FrmCleanDatabase().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        AfrmDashboard frmDashboard = new AfrmDashboard();
        frmDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3KeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        FrmManageUser frmManageUser = new FrmManageUser();
        frmManageUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to reset the database?", "Clear database", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "The database will be reset. For security purpose, please enter admin credential for authentication.", "Clear membership details and payment history", JOptionPane.WARNING_MESSAGE);
                String username = JOptionPane.showInputDialog(rootPane, "Please enter your username.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                
                Category category = new Category();
                Product product = new Product();
                Feedback feedback = new Feedback();
                Payment payment = new Payment();
                Customer customer = new Customer();
                Appointment appointment = new Appointment();
                Validation check = new Validation();
                if (confirmed == JOptionPane.YES_OPTION) {
                    String password = JOptionPane.showInputDialog(rootPane, "Please enter your password.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                    if (!username.equals("") && !password.equals("")) {
                        if (check.adminCheck(username, password)) {
                            category.ClearCategoryDatabase();
                            product.ClearProductDatabase();
                            feedback.ClearFeedbackDatabase();
                            payment.ClearPaymentDatabase();
                            customer.ClearCustomerDatabase();
                            Admin User = new Admin();
                            User.ClearUserDatabase(Global.login_id);
                            appointment.ClearAppointmentDatabase();
                            JOptionPane.showMessageDialog(null, "Database had been reset");
                            new FrmCleanDatabase().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "The username or password is incorrect.", "Authentication failed", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "You have canceled the action.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cancel Reset");
        }
        
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete all category and product details from the system?", "Clear database", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "All category and product details will be deleted from database as well as the activities details. For security purpose, please enter admin credential for authentication.", "Clear membership details and payment history", JOptionPane.WARNING_MESSAGE);
                String username = JOptionPane.showInputDialog(rootPane, "Please enter your username.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                Category category = new Category();
                Product product = new Product();
                Validation check = new Validation();
                if (confirmed == JOptionPane.YES_OPTION) {
                    String password = JOptionPane.showInputDialog(rootPane, "Please enter your password.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                    if (!username.equals("") && !password.equals("")) {
                        if (check.adminCheck(username, password)) {
                            category.ClearCategoryDatabase();
                            product.ClearProductDatabase();
                            JOptionPane.showMessageDialog(null, "Both category and product details had been deleted");
                            new FrmCleanDatabase().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "The username or password is incorrect.", "Authentication failed", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "You have canceled the action.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cancel deletion of category and product details");
        }
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnClean1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClean1ActionPerformed
        // TODO add your handling code here:
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete all payment and feedback details from the system?", "Clear database", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "All payment and feedback details will be deleted from database. For security purpose, please enter admin credential for authentication.", "Clear membership details and payment history", JOptionPane.WARNING_MESSAGE);
                String username = JOptionPane.showInputDialog(rootPane, "Please enter your username.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                
                Payment payment = new Payment();
                Feedback feedback = new Feedback();
                
                Validation check = new Validation();
                if (confirmed == JOptionPane.YES_OPTION) {
                    String password = JOptionPane.showInputDialog(rootPane, "Please enter your password.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                    if (!username.equals("") && !password.equals("")) {
                        if (check.adminCheck(username, password)) {
                            payment.ClearPaymentDatabase();
                            feedback.ClearFeedbackDatabase();
                            JOptionPane.showMessageDialog(null, "Both payment and feedback details had been deleted");
                            new FrmCleanDatabase().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "The username or password is incorrect.", "Authentication failed", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "You have canceled the action.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cancel deletion of payment and feedback details");
        }
    }//GEN-LAST:event_btnClean1ActionPerformed

    private void btnClean2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClean2ActionPerformed
        // TODO add your handling code here:
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete all member and appointment details from the system?", "Clear database", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "All member details will be deleted from database as well as all appointment details. For security purpose, please enter admin credential for authentication.", "Clear membership details and payment history", JOptionPane.WARNING_MESSAGE);
                String username = JOptionPane.showInputDialog(rootPane, "Please enter your username.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                
                Customer customer = new Customer();
                Appointment appointment = new Appointment();
                Validation check = new Validation();
                if (confirmed == JOptionPane.YES_OPTION) {
                    String password = JOptionPane.showInputDialog(rootPane, "Please enter your password.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                    if (!username.equals("") && !password.equals("")) {
                        if (check.adminCheck(username, password)) {
                            customer.ClearCustomerDatabase();
                            appointment.ClearAppointmentDatabase();
                            JOptionPane.showMessageDialog(null, "Both member and appointment details had been deleted");
                            new FrmCleanDatabase().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "The username or password is incorrect.", "Authentication failed", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "You have canceled the action.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cancel deletion of member and appointment details");
        }
        
    }//GEN-LAST:event_btnClean2ActionPerformed

    private void btnClean3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClean3ActionPerformed
        // TODO add your handling code here:
        
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete all system user details from the system?", "Clear database", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "All system user details will be deleted from database. For security purpose, please enter admin credential for authentication.", "Clear membership details and payment history", JOptionPane.WARNING_MESSAGE);
                String username = JOptionPane.showInputDialog(rootPane, "Please enter your username.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                
                Validation check = new Validation();
                if (confirmed == JOptionPane.YES_OPTION) {
                    String password = JOptionPane.showInputDialog(rootPane, "Please enter your password.", "Authorized account only", JOptionPane.WARNING_MESSAGE);
                    if (!username.equals("") && !password.equals("")) {
                        if (check.adminCheck(username, password)) {
                            Admin User = new Admin();
                            User.ClearUserDatabase(Global.login_id);
                            JOptionPane.showMessageDialog(null, "System user details had been deleted");
                            new FrmCleanDatabase().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "The username or password is incorrect.", "Authentication failed", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "You have canceled the action.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cancel deletion of system user details");
        }
        
    }//GEN-LAST:event_btnClean3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCleanDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCleanDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCleanDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCleanDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCleanDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClean1;
    private javax.swing.JButton btnClean2;
    private javax.swing.JButton btnClean3;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
