/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Administrator.AfrmDashboard;
import Config.Global;
import Classes.Constant;
import Classes.Technician;
import Classes.User;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class FrmUpdateTechnician extends javax.swing.JFrame {

    /**
     * Creates new form frmUpdateTechnician
     */
    public FrmUpdateTechnician() {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);

        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.UpdateTechnician);
        txtRole.setText(con.Technician);
        jLabel4.setText(con.Security);
        jLabel19.setText(con.Question);
        jLabel20.setText(con.Answer);
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRole = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        btnActivate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        txtDOB = new org.gui.JCalendarCombo();
        chkPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        txtCPassword = new javax.swing.JPasswordField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("User ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 120, 110, 17);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Username");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 160, 80, 17);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("Date of Birth");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 200, 90, 17);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("Password");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 240, 150, 17);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Confirm Password");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 280, 150, 17);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("Role");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 320, 150, 17);

        txtRole.setText("jLabel20");
        jPanel2.add(txtRole);
        txtRole.setBounds(190, 320, 290, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 430, 400, 60);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("jLabel16");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 510, 150, 17);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setText("jLabel15");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 550, 150, 17);

        txtAnswer.setEditable(false);
        jPanel2.add(txtAnswer);
        txtAnswer.setBounds(180, 540, 300, 40);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Status");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(500, 120, 110, 17);

        txtUserID.setEditable(false);
        txtUserID.setForeground(new java.awt.Color(153, 153, 153));
        txtUserID.setText("AUTO-GENRATED");
        jPanel2.add(txtUserID);
        txtUserID.setBounds(180, 110, 300, 40);

        txtUsername.setEditable(false);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernametxtUserIDFocusLost(evt);
            }
        });
        jPanel2.add(txtUsername);
        txtUsername.setBounds(180, 150, 300, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("ACTIVE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(630, 120, 70, 17);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(640, 690, 120, 50);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("BACK");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(40, 10, 40, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        txtQuestion.setEditable(false);
        jPanel2.add(txtQuestion);
        txtQuestion.setBounds(180, 500, 300, 40);

        btnActivate.setBackground(java.awt.Color.green);
        btnActivate.setText("ACTIVATE");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateActionPerformed(evt);
            }
        });
        jPanel2.add(btnActivate);
        btnActivate.setBounds(10, 690, 140, 50);

        btnDeactivate.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        btnDeactivate.setText("DEACTIVATE");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeactivate);
        btnDeactivate.setBounds(160, 690, 140, 50);
        jPanel2.add(txtDOB);
        txtDOB.setBounds(190, 200, 290, 26);

        chkPassword.setText("View Password");
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(chkPassword);
        chkPassword.setBounds(490, 240, 140, 23);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(180, 230, 300, 40);
        jPanel2.add(txtCPassword);
        txtCPassword.setBounds(180, 270, 300, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernametxtUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernametxtUserIDFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsernametxtUserIDFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();
        String Status = jLabel5.getText();
        ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add(Status);
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();
        
        if(Global.role.equals("ADMIN")) {
            new AfrmDashboard().setVisible(true);
        } else {
            new FrmManageTechnician().setVisible(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        if(Global.role.equals("ADMIN")) {
            new AfrmDashboard().setVisible(true);
        } else {
            new FrmManageTechnician().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();
        
        ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add("ACTIVE");
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();
        
        if(Global.role.equals("ADMIN")) {
            new AfrmDashboard().setVisible(true);
        } else {
            new FrmManageTechnician().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnActivateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();
        
        ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add("INACTIVE");
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();
        
        if(Global.role.equals("ADMIN")) {
            new AfrmDashboard().setVisible(true);
        } else {
            new FrmManageTechnician().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        // TODO add your handling code here:
        if (chkPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
            txtCPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
            txtCPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTechnician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTechnician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTechnician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTechnician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUpdateTechnician().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivate;
    public javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txtAnswer;
    public javax.swing.JPasswordField txtCPassword;
    public org.gui.JCalendarCombo txtDOB;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtQuestion;
    public javax.swing.JLabel txtRole;
    public javax.swing.JTextField txtUserID;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
