/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import Config.Global;
import DataAccess.DataAccess;
import Classes.Account;
import Classes.Appointment;
import Classes.Category;
import Classes.Constant;
import Classes.Customer;
import Classes.Initials;
import Classes.Technician;
import Classes.TotalRecords;
import Classes.User;
import Classes.Validation;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class FrmAppointment extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    private static boolean checked = false;

    /**
     * Creates new form frmAppointment
     */
    public FrmAppointment() {
        Constant con = new Constant();
        Initials GetInitials = new Initials();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();

        txtAppointmentID.setText(GetInitials.getAppointID());

        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.Appointment);
        jLabel25.setText(Global.role);

        lblRole.setText(Global.name);

        Customer customer = new Customer();
        cmbCustomerName.setModel(customer.getCustomerNameforComboBox());
        Category category = new Category();
        cmbCategoryName.setModel(category.getCategoryNameforComboBox());
        Technician technician = new Technician();
        cmbTechnicianName.setModel(technician.getTechnicianNameforComboBox());
        RemoveTechnician();

        int Hours = Integer.parseInt(txtHours.getSelectedItem().toString());
        int Duration = Integer.parseInt(cmbDuration.getSelectedItem().toString());
        String Minutes = cmbMinutes.getSelectedItem().toString();
        int EndTime = Hours + Duration;
        lblEndTime.setText(EndTime + Minutes + "");
    }

    private void RemoveTechnician() {
        da.setFileName("Appointment.txt");
        TotalRecords TR = new TotalRecords();
        String[] OccupiedTechnician = new String[TR.GetTotalAppointment()];
        String AppointmentDate = txtAppointmentDate.getSelectedDate().toString();
        String StartTime = txtHours.getSelectedItem().toString() + cmbMinutes.getSelectedItem().toString();
        int startTime = Integer.parseInt(StartTime);
        ArrayList<String> TechnicianWithAppointment = da.readAll();
        for (int i = 0; i < TechnicianWithAppointment.size(); i++) {
            String[] split = TechnicianWithAppointment.get(i).split("\\|");
            if (split[9].equals("PENDING")) {
                int EndTime = Integer.parseInt(split[8]);
                if (split[6].compareTo(AppointmentDate) == 0) {
                    if (EndTime > startTime) {
                        OccupiedTechnician[i] = split[3];
                    }
                }
            }

        }
        for (String rec : OccupiedTechnician) {
            cmbTechnicianName.removeItem(rec);
        }

    }

    public void CurrentDateandTime() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " + day + "/" + (month + 1) + "/" + year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: " + hour + ":" + (minute) + ":" + second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
        clock.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAppointmentID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbCustomerName = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbCategoryName = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cmbTechnicianName = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtCarPlateNo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtAppointmentDetails = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAppointmentDate = new org.gui.JCalendarCombo();
        jLabel24 = new javax.swing.JLabel();
        cmbMinutes = new javax.swing.JComboBox<>();
        txtHours = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnView3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbDuration = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 17);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 255, 0));
        lblRole.setText("jLabel2");
        jPanel1.add(lblRole);
        lblRole.setBounds(10, 40, 200, 40);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Manage Appointment");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10);
        jLabel10.setBounds(60, 10, 150, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 320, 250, 50);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Catogery");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 170, 130, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage Product");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Customer");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 270, 130, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Manage Payment");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 380, 120, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PROFILE");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 660, 60, 20);

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("jLabel20");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(140, 10, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 750);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("LOGOUT");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(30, 10, 70, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        txtAppointmentID.setEditable(false);
        txtAppointmentID.setForeground(new java.awt.Color(153, 153, 153));
        txtAppointmentID.setText("AUTO-GENRATED");
        jPanel2.add(txtAppointmentID);
        txtAppointmentID.setBounds(180, 110, 240, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Customer Name");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 160, 130, 17);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Appointment ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 120, 110, 17);

        jPanel2.add(cmbCustomerName);
        cmbCustomerName.setBounds(180, 160, 240, 27);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("Car Plate No");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 240, 130, 17);

        jPanel2.add(cmbCategoryName);
        cmbCategoryName.setBounds(180, 200, 240, 27);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setText("Category Name");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 200, 110, 17);

        cmbTechnicianName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTechnicianNameActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTechnicianName);
        cmbTechnicianName.setBounds(190, 480, 220, 27);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Technician Name");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 480, 130, 17);

        txtCarPlateNo.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtCarPlateNo);
        txtCarPlateNo.setBounds(180, 230, 240, 40);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("Appointment Details");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 280, 150, 17);

        txtAppointmentDetails.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtAppointmentDetails);
        txtAppointmentDetails.setBounds(180, 270, 240, 40);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Appointment Time");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 360, 130, 17);

        txtAppointmentDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoursMouseClicked(evt);
            }
        });
        txtAppointmentDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAppointmentDateKeyPressed(evt);
            }
        });
        jPanel2.add(txtAppointmentDate);
        txtAppointmentDate.setBounds(190, 320, 220, 26);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel24.setText("Appointment Date");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 320, 130, 17);

        cmbMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));
        cmbMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDurationActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMinutes);
        cmbMinutes.setBounds(300, 360, 110, 27);

        txtHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09", "10", "11", "12", "13", "14", "15", "16", "17" }));
        txtHours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoursMouseClicked(evt);
            }
        });
        txtHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDurationActionPerformed(evt);
            }
        });
        jPanel2.add(txtHours);
        txtHours.setBounds(190, 360, 100, 27);

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreate);
        btnCreate.setBounds(640, 690, 120, 50);

        btnView3.setText("VIEW");
        btnView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnView3);
        btnView3.setBounds(10, 690, 120, 50);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Duration");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 400, 70, 17);

        cmbDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDurationActionPerformed(evt);
            }
        });
        jPanel2.add(cmbDuration);
        cmbDuration.setBounds(190, 400, 220, 27);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("End Time");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 440, 90, 17);

        lblEndTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(lblEndTime);
        lblEndTime.setBounds(200, 440, 200, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        FrmCategory frmCategory = new FrmCategory();
        frmCategory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new FrmProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new FrmCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Account Logout", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                Account account = new Account();
                account.logout(Global.user_login_id);
                frmLogin.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid logged out. Please launch the program from login page.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new FrmAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        TfrmDashboard TfrmDashboard = new TfrmDashboard();
        TfrmDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String AppointmentID = txtAppointmentID.getText();
        String CustomerName = cmbCustomerName.getSelectedItem().toString();
        String CategoryName = cmbCategoryName.getSelectedItem().toString();
        String TechnicianName = cmbTechnicianName.getSelectedItem().toString();
        String CarPlateNo = txtCarPlateNo.getText().toUpperCase();
        String AppointmentDetail = txtAppointmentDetails.getText();
        String AppointmentDate = txtAppointmentDate.getSelectedDate();
        String StartTime = (txtHours.getSelectedItem().toString() + cmbMinutes.getSelectedItem().toString());
        String EndTime = lblEndTime.getText();
        String status = "PENDING";

        Validation check = new Validation();
        Customer customer = new Customer();
//        Appointment Appointment = new Appointment(AppointmentID, CustomerName, CategoryName, TechnicianName, CarPlateNo, AppointmentDetails, AppointmentDate, StartTime, EndTime, "PENDING");
        try {
            if (check.checkAppointmentDate(AppointmentDate)) {
                if (!CarPlateNo.isEmpty() && !AppointmentDetail.isEmpty() && !TechnicianName.isEmpty() && !CategoryName.isEmpty() && !CustomerName.isEmpty()) {
//                    Appointment.Add();
                    ArrayList<String> ApppointmentDetails;
                    ApppointmentDetails = new ArrayList<>();
                    ApppointmentDetails.add(AppointmentID);
                    ApppointmentDetails.add(CustomerName);
                    ApppointmentDetails.add(CategoryName);
                    ApppointmentDetails.add(TechnicianName);
                    ApppointmentDetails.add(CarPlateNo);
                    ApppointmentDetails.add(AppointmentDetail);
                    ApppointmentDetails.add(AppointmentDate);
                    ApppointmentDetails.add(StartTime);
                    ApppointmentDetails.add(EndTime);
                    ApppointmentDetails.add(status);
                    Appointment appointment = new Appointment(ApppointmentDetails);
                    appointment.Add();
                    customer.UpdateAppointment(CustomerName, AppointmentID);
                    JOptionPane.showMessageDialog(rootPane, "One appointment is added", "Appointment Added", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new FrmAppointment().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Please make sure that you have entered all the fields!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please make sure that you have chosen the day after.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView3ActionPerformed
        // TODO add your handling code here:
        new FrmViewAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnView3ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        new FrmPayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void cmbDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDurationActionPerformed
        // TODO add your handling code here:
        String Hours = txtHours.getSelectedItem().toString();
        int hours = Integer.parseInt(Hours);
        String Duration = cmbDuration.getSelectedItem().toString();
        int duration = Integer.parseInt(Duration);
        int EndTime = hours + duration;
        String endTime = Integer.toString(EndTime);
        lblEndTime.setText(endTime + cmbMinutes.getSelectedItem().toString());

        cmbTechnicianName.removeAllItems();
        Technician technician = new Technician();
        cmbTechnicianName.setModel(technician.getTechnicianNameforComboBox());
        RemoveTechnician();

    }//GEN-LAST:event_cmbDurationActionPerformed

    private void cmbTechnicianNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTechnicianNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbTechnicianNameActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        try {
            // TODO add your handling code here:
            new PROFILE().setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(FrmAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtAppointmentDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppointmentDateKeyPressed


    }//GEN-LAST:event_txtAppointmentDateKeyPressed

    private void txtHoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoursMouseClicked
        // TODO add your handling code here:

        cmbTechnicianName.removeAllItems();
        Technician technician = new Technician();
        cmbTechnicianName.setModel(technician.getTechnicianNameforComboBox());
        RemoveTechnician();


    }//GEN-LAST:event_txtHoursMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView3;
    private javax.swing.JComboBox<String> cmbCategoryName;
    private javax.swing.JComboBox<String> cmbCustomerName;
    private javax.swing.JComboBox<String> cmbDuration;
    private javax.swing.JComboBox<String> cmbMinutes;
    private javax.swing.JComboBox<String> cmbTechnicianName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblRole;
    private org.gui.JCalendarCombo txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentDetails;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtCarPlateNo;
    private javax.swing.JLabel txtDate;
    private javax.swing.JComboBox<String> txtHours;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
