/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import DataAccess.DataAccess;
import Classes.Constant;
import Classes.Feedback;
import Classes.Initials;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kianjun
 */
public class FrmFeedback extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    private static String AppointmentID;
    private int Rate = 3;
    /**
     * Creates new form frmFeedback
     */
    public FrmFeedback(String AppointmentID) {
        this.AppointmentID = AppointmentID;
        Constant con = new Constant();
        Initials GetInitials = new Initials();
        initComponents();
        this.setLocationRelativeTo(null);

        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.MakeFeedback);
        
        txtFeedbackID.setText(GetInitials.getFeedbackID());
        txtCategoryName.setText(AppointmentID);
        
        String pattern = "dd/MM/yyyy";
        String regDate = new SimpleDateFormat(pattern).format(new Date());
        
        txtDateAdded.setText(regDate);
        getDetails(AppointmentID);
    }
    
    private void getDetails(String AppointmentID) {
        da.setFileName("Appointment.txt");
        ArrayList<String> data = da.readAll();
        for(String rec: data) {
            String[] split = rec.split("\\|");
            if(split[0].equals(AppointmentID)) {
                txtAppointmentID.setText(split[0]);
                txtCustomerName.setText(split[1]);
                txtCategoryName.setText(split[2]);
                txtTechnicianName.setText(split[3]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtFeedbackID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCategoryName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDateAdded = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTechnicianName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtImprovement = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedbackDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtAppointmentID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Appointment ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 160, 130, 17);

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);
        btnSubmit.setBounds(640, 690, 120, 50);

        txtFeedbackID.setEditable(false);
        txtFeedbackID.setForeground(new java.awt.Color(153, 153, 153));
        txtFeedbackID.setText("AUTO-GENRATED");
        jPanel2.add(txtFeedbackID);
        txtFeedbackID.setBounds(140, 110, 240, 40);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("Feedback ID");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 120, 130, 17);

        txtCustomerName.setEditable(false);
        txtCustomerName.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtCustomerName);
        txtCustomerName.setBounds(140, 440, 240, 40);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setText("Tell us what we can improve");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 570, 200, 17);

        buttonGroup1.add(rbtn1);
        rbtn1.setText("Not at all satisfied");
        rbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(rbtn1);
        rbtn1.setBounds(140, 240, 160, 23);

        buttonGroup1.add(rbtn2);
        rbtn2.setText("Partly satisfied");
        rbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(rbtn2);
        rbtn2.setBounds(140, 270, 150, 23);

        buttonGroup1.add(rbtn3);
        rbtn3.setSelected(true);
        rbtn3.setText("Satisfied");
        rbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(rbtn3);
        rbtn3.setBounds(140, 300, 86, 23);

        buttonGroup1.add(rbtn4);
        rbtn4.setText("More than satisfied");
        rbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(rbtn4);
        rbtn4.setBounds(140, 330, 160, 23);

        buttonGroup1.add(rbtn5);
        rbtn5.setText("Very satisfied");
        rbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(rbtn5);
        rbtn5.setBounds(140, 360, 117, 23);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Customer Name");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 450, 120, 17);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("Rating");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 240, 120, 17);

        txtCategoryName.setEditable(false);
        txtCategoryName.setForeground(new java.awt.Color(153, 153, 153));
        txtCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtCategoryName);
        txtCategoryName.setBounds(140, 190, 240, 40);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Date");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 410, 120, 17);

        txtDateAdded.setEditable(false);
        txtDateAdded.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtDateAdded);
        txtDateAdded.setBounds(140, 400, 240, 40);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel24.setText("Technician Name");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 490, 120, 17);

        txtTechnicianName.setEditable(false);
        txtTechnicianName.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtTechnicianName);
        txtTechnicianName.setBounds(140, 480, 240, 40);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 540, 770, 12);
        jPanel2.add(txtImprovement);
        txtImprovement.setBounds(220, 560, 290, 40);

        jLabel1.setText("Feedback Description");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 610, 150, 16);

        txtFeedbackDescription.setColumns(20);
        txtFeedbackDescription.setRows(5);
        jScrollPane1.setViewportView(txtFeedbackDescription);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(220, 610, 290, 90);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Category Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 200, 110, 17);

        txtAppointmentID.setEditable(false);
        txtAppointmentID.setForeground(new java.awt.Color(153, 153, 153));
        txtAppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtAppointmentID);
        txtAppointmentID.setBounds(140, 150, 240, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String FeedbackID = txtFeedbackID.getText();
        String CategoryName = txtCategoryName.getText();
        String FeedbackDescription = txtFeedbackDescription.getText();
        String Improvement = txtImprovement.getText();
        String DateAdded = txtDateAdded.getText();
        String CustomerName = txtCustomerName.getText();
        String TechnicianName = txtTechnicianName.getText();
        String Rating = Integer.toString(Rate);
        
        ArrayList<String> FeedbackDetails;
        FeedbackDetails = new ArrayList<>();
        FeedbackDetails.add(FeedbackID);
        FeedbackDetails.add(AppointmentID);
        FeedbackDetails.add(CategoryName);
        FeedbackDetails.add(FeedbackDescription);
        FeedbackDetails.add(Rating);
        FeedbackDetails.add(Improvement);
        FeedbackDetails.add(DateAdded);
        FeedbackDetails.add(CustomerName);
        FeedbackDetails.add(TechnicianName);
        
        try {
            if(!FeedbackDescription.isEmpty() && !Improvement.isEmpty()) {
                Feedback feedback = new Feedback(FeedbackDetails);
//                Feedback feedback = new Feedback(FeedbackID, AppointmentID, CategoryName, FeedbackDescription, Rating, Improvement, DateAdded, CustomerName, TechnicianName);
                feedback.Add();
                new FrmPayment().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please make sure that you give us Improvement and Feedback Description as feedback !");
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1ActionPerformed
        // TODO add your handling code here:
        Rate = 1;
    }//GEN-LAST:event_rbtn1ActionPerformed

    private void rbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn2ActionPerformed
        // TODO add your handling code here:
        Rate = 2;
    }//GEN-LAST:event_rbtn2ActionPerformed

    private void rbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn3ActionPerformed
        // TODO add your handling code here:
        Rate = 3;
    }//GEN-LAST:event_rbtn3ActionPerformed

    private void rbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn4ActionPerformed
        // TODO add your handling code here:
        Rate = 4;
    }//GEN-LAST:event_rbtn4ActionPerformed

    private void rbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn5ActionPerformed
        // TODO add your handling code here:
        Rate = 5;
    }//GEN-LAST:event_rbtn5ActionPerformed

    private void txtAppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentIDActionPerformed

    private void txtCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFeedback(AppointmentID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDateAdded;
    private javax.swing.JTextArea txtFeedbackDescription;
    private javax.swing.JTextField txtFeedbackID;
    private javax.swing.JTextField txtImprovement;
    private javax.swing.JTextField txtTechnicianName;
    // End of variables declaration//GEN-END:variables
}
