/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import Config.Global;
import DataAccess.DataAccess;
import Classes.Account;
import Classes.Appointment;
import Classes.Constant;
import Classes.Customer;
import Classes.Initials;
import Classes.Payment;
import Classes.Product;
import Classes.User;
import com.sun.glass.events.KeyEvent;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class FrmPayment extends javax.swing.JFrame {

    DataAccess da = new DataAccess();

    /**
     * Creates new form frmPayment
     */
    public FrmPayment() {
        Constant con = new Constant();
        Initials GetInitials = new Initials();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();

        txtPaymentID.setText(GetInitials.getPaymentID());

        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.AddPayment);

        lblRole.setText(Global.name);
        jLabel34.setText(Global.role);

        Product product = new Product();
        cmbProductName.setModel(product.getProductNameforComboBox());
        Appointment appointment = new Appointment();
        cmbAppointmentID.setModel(appointment.getAppointmentIDforComboBox());
    }

    public void CurrentDateandTime() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " + day + "/" + (month + 1) + "/" + year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: " + hour + ":" + (minute) + ":" + second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
        clock.start();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbAppointmentID = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbProductName = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTotal6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtCategoryPrice = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtProductQuantity = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 17);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 255, 0));
        lblRole.setText("jLabel2");
        jPanel1.add(lblRole);
        lblRole.setBounds(10, 40, 200, 40);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Manage Payment");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13);
        jLabel13.setBounds(80, 10, 120, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 380, 250, 50);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Catogery");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 170, 130, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage Product");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Customer");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 270, 130, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Manage Appointment");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 330, 150, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PROFILE");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 660, 60, 20);

        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("jLabel20");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(140, 10, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 750);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("LOGOUT");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(30, 10, 70, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        txtPaymentID.setEditable(false);
        txtPaymentID.setForeground(new java.awt.Color(153, 153, 153));
        txtPaymentID.setText("AUTO-GENRATED");
        jPanel2.add(txtPaymentID);
        txtPaymentID.setBounds(180, 110, 240, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Appointment ID");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 160, 130, 17);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Payment ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 120, 110, 17);

        cmbAppointmentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbAppointmentIDFocusLost(evt);
            }
        });
        cmbAppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAppointmentIDActionPerformed(evt);
            }
        });
        jPanel2.add(cmbAppointmentID);
        cmbAppointmentID.setBounds(180, 160, 240, 27);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("Category Price");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 280, 130, 17);

        cmbProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductNameActionPerformed(evt);
            }
        });
        jPanel2.add(cmbProductName);
        cmbProductName.setBounds(180, 400, 240, 27);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setText("Customer Name");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 200, 110, 17);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Category Name");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 240, 130, 17);

        txtTotal6.setEditable(false);
        txtTotal6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtTotal6);
        txtTotal6.setBounds(230, 590, 190, 40);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("Appointment Date");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 320, 150, 17);

        txtAppointmentDate.setEditable(false);
        txtAppointmentDate.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtAppointmentDate);
        txtAppointmentDate.setBounds(180, 310, 240, 40);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel24.setText("Appointment Time");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 360, 130, 17);

        btnCreate.setText("PROCEED");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreate);
        btnCreate.setBounds(640, 690, 120, 50);

        btnView3.setText("VIEW");
        btnView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnView3);
        btnView3.setBounds(10, 690, 120, 50);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel25.setText("Product Name");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 400, 130, 17);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel26.setText("Product Price");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 440, 130, 17);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel27.setText("Quantity (Available)");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(10, 480, 150, 17);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Total (After Tax 6%)");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 600, 150, 17);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel28.setText("RM");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(190, 440, 30, 17);

        txtCategoryPrice.setEditable(false);
        txtCategoryPrice.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtCategoryPrice);
        txtCategoryPrice.setBounds(230, 270, 190, 40);

        txtCustomerName.setEditable(false);
        txtCustomerName.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtCustomerName);
        txtCustomerName.setBounds(180, 190, 240, 40);

        txtCategoryName.setEditable(false);
        txtCategoryName.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtCategoryName);
        txtCategoryName.setBounds(180, 230, 240, 40);

        txtAppointmentTime.setEditable(false);
        txtAppointmentTime.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtAppointmentTime);
        txtAppointmentTime.setBounds(180, 350, 240, 40);

        txtProductPrice.setEditable(false);
        txtProductPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtProductPrice.setText("N/P");
        jPanel2.add(txtProductPrice);
        txtProductPrice.setBounds(230, 430, 190, 40);

        txtProductQuantity.setEditable(false);
        txtProductQuantity.setForeground(new java.awt.Color(153, 153, 153));
        txtProductQuantity.setText("N/P");
        jPanel2.add(txtProductQuantity);
        txtProductQuantity.setBounds(180, 470, 240, 40);

        txtTotal.setEditable(false);
        txtTotal.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(txtTotal);
        txtTotal.setBounds(230, 550, 190, 40);

        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        jPanel2.add(txtQuantity);
        txtQuantity.setBounds(180, 510, 140, 40);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel29.setText("How much you want");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(10, 520, 150, 17);

        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculate);
        btnCalculate.setBounds(320, 509, 100, 40);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel30.setText("Total");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(10, 560, 130, 17);

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel31.setText("RM");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(190, 560, 30, 17);

        jLabel32.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel32.setText("RM");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(190, 600, 30, 17);

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel33.setText("RM");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(190, 280, 30, 17);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new FrmAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        FrmCategory frmCategory = new FrmCategory();
        frmCategory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new FrmProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new FrmCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        TfrmDashboard TfrmDashboard = new TfrmDashboard();
        TfrmDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Account Logout", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                Account account = new Account();
                account.logout(Global.user_login_id);
                frmLogin.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid logged out. Please launch the program from login page.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        try {
            String pattern = "dd/MM/yyyy";
            String regDate = new SimpleDateFormat(pattern).format(new Date());
            String PaymentID = txtPaymentID.getText();
            String AppointmentID = cmbAppointmentID.getSelectedItem().toString();
            String CustomerName = txtCustomerName.getText();
            String CategoryName = txtCategoryName.getText();
            String CategoryPrice = txtCategoryPrice.getText();
            String AppointmentDate = txtAppointmentDate.getText();
            String AppointmentTime = txtAppointmentTime.getText();
            String ProductName = cmbProductName.getSelectedItem().toString();
            String ProductPrice = txtProductPrice.getText();
            String ProductQuantity = txtProductQuantity.getText();
            String Quantity = txtQuantity.getText();
            String Total = txtTotal6.getText();
            String Status = "ACTIVE";

            if (!ProductPrice.equals("N/P")) {
                ArrayList<String> PaymentDetails;
                PaymentDetails = new ArrayList<>();
                PaymentDetails.add(PaymentID);
                PaymentDetails.add(AppointmentID);
                PaymentDetails.add(CustomerName);
                PaymentDetails.add(CategoryName);
                PaymentDetails.add(CategoryPrice);
                PaymentDetails.add(AppointmentDate);
                PaymentDetails.add(AppointmentTime);
                PaymentDetails.add(ProductName);
                PaymentDetails.add(ProductPrice);
                PaymentDetails.add(Quantity);
                PaymentDetails.add(regDate);
                PaymentDetails.add(Total);
                PaymentDetails.add(Status);
                Payment Payment = new Payment(PaymentDetails);
//                Payment Payment = new Payment(PaymentID, AppointmentID, CustomerName, CategoryName, CategoryPrice, AppointmentDate, AppointmentTime, ProductName, ProductPrice, Quantity, regDate, Total, Status);
                Payment.Add();
                Customer customer = new Customer();
                customer.RemoveAppointment(CustomerName);
                Appointment appointment = new Appointment();
                appointment.RemoveAppointment(AppointmentID);
                Product Product = new Product();
                Product.UpdateProductQuantity(ProductName, Quantity);
            } else {
                ArrayList<String> PaymentDetails;
                PaymentDetails = new ArrayList<>();
                PaymentDetails.add(PaymentID);
                PaymentDetails.add(AppointmentID);
                PaymentDetails.add(CustomerName);
                PaymentDetails.add(CategoryName);
                PaymentDetails.add(CategoryPrice);
                PaymentDetails.add(AppointmentDate);
                PaymentDetails.add(AppointmentTime);
                PaymentDetails.add(ProductName);
                PaymentDetails.add(ProductPrice);
                PaymentDetails.add(ProductQuantity);
                PaymentDetails.add(regDate);
                PaymentDetails.add(Total);
                PaymentDetails.add(Status);
                Payment Payment = new Payment(PaymentDetails);
//                Payment Payment = new Payment(PaymentID, AppointmentID, CustomerName, CategoryName, CategoryPrice, AppointmentDate, AppointmentTime, ProductName, ProductPrice, ProductQuantity, regDate, Total, Status);
                Payment.Add();
                Customer customer = new Customer();
                customer.RemoveAppointment(CustomerName);
                Appointment appointment = new Appointment();
                appointment.RemoveAppointment(AppointmentID);
            }

            new FrmPaymentMethod(AppointmentID).setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView3ActionPerformed
        // TODO add your handling code here:
        new FrmViewPayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnView3ActionPerformed

    private void cmbProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductNameActionPerformed
        // TODO add your handling code here:
        String ProductName = cmbProductName.getSelectedItem().toString();

        try {
            da.setFileName("Product.txt");
            ArrayList<String> data = da.readAll();
            for (String rec : data) {
                String[] split = rec.split("\\|");
                if (split[2].equals(ProductName)) {
                    txtProductPrice.setText(split[5]);
                    txtProductQuantity.setText(split[6]);
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbProductNameActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new FrmPayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void cmbAppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAppointmentIDActionPerformed
        // TODO add your handling code here:
        String AppointmentID = cmbAppointmentID.getSelectedItem().toString();
        try {
            da.setFileName("Appointment.txt");
            ArrayList<String> data = da.readAll();
            for (String rec : data) {
                String[] split = rec.split("\\|");
                if (split[0].equals(AppointmentID)) {
                    txtCustomerName.setText(split[1]);
                    txtCategoryName.setText(split[2]);
                    getCategoryPrice();
                    txtAppointmentDate.setText(split[6]);
                    txtAppointmentTime.setText(split[7]);

                    txtTotal.setText(txtCategoryPrice.getText());
                    double total = Double.parseDouble(txtCategoryPrice.getText());
                    double sixPercent = total * 1.06;
                    sixPercent = Math.round(sixPercent * 100.0) / 100.0;
                    txtTotal6.setText(sixPercent + "");
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmbAppointmentIDActionPerformed

    private void cmbAppointmentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbAppointmentIDFocusLost
        // TODO add your handling code here:
        da.setFileName("Category.txt");
        ArrayList<String> data = da.readAll();
        for (String rec : data) {
            String[] split = rec.split("\\|");
            if (split[1].equals(txtCategoryName.getText())) {
                txtCategoryPrice.setText(split[4]);
                break;
            }
        }
    }//GEN-LAST:event_cmbAppointmentIDFocusLost

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtQuantityFocusLost

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtQuantityKeyReleased

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
            int Total = Integer.parseInt(txtCategoryPrice.getText());
            int Price = Integer.parseInt(txtProductPrice.getText());
            int ProductQuantity = Integer.parseInt(txtProductQuantity.getText());
            int Quantity = Integer.parseInt(txtQuantity.getText());
            double Total1 = 0.0;
            double Total6;
            if (!txtQuantity.getText().isEmpty()) {
                if (Quantity <= ProductQuantity) {
                    txtTotal.setText("");
                    txtTotal6.setText("");
                    Total1 = Price * Quantity;
                    Total1 += Total;
                    txtTotal.setText(Total1 + "");
                    Total6 = (Total + Price * Quantity) * 1.06;
                    Total6 = Math.round(Total6 * 100.0) / 100.0;
                    txtTotal6.setText(Total6 + "");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Please ensure that you have entered the value below the stock available.");
                }
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c)) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        try {
            // TODO add your handling code here:
            new PROFILE().setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(FrmPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void getCategoryPrice() {
        da.setFileName("Category.txt");
        ArrayList<String> data = da.readAll();
        for (String rec : data) {
            String[] split = rec.split("\\|");
            if (split[1].equals(txtCategoryName.getText())) {
                txtCategoryPrice.setText(split[4]);
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView3;
    private javax.swing.JComboBox<String> cmbAppointmentID;
    private javax.swing.JComboBox<String> cmbProductName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtCategoryPrice;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JLabel txtTime;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal6;
    // End of variables declaration//GEN-END:variables
}
