/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import Classes.Appointment;
import Classes.Constant;
import DataAccess.DataAccess;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kianjun
 */
public class FrmUpdateAppointment extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    private static String AppointmentID, CustomerName, CategoryName, TechnicianName, CarPlateNo, AppointmentDetail, AppointmentDate, AppointmentTime, Endtime, Status;

    /**
     * Creates new form frmUpdateAppointment
     */
    public FrmUpdateAppointment(String AppointmentID, String CustomerName, String CategoryName, String TechnicianName, String CarPlateNo, String AppointmentDetails, String AppointmentDate, String AppointmentTime, String Endtime, String Status) {
        this.AppointmentID = AppointmentID;
        this.CustomerName = CustomerName;
        this.CategoryName = CategoryName;
        this.TechnicianName = TechnicianName;
        this.CarPlateNo = CarPlateNo;
        this.AppointmentDetail = AppointmentDetails;
        this.AppointmentTime = AppointmentTime;
        this.AppointmentDate = AppointmentDate;
        this.Endtime = Endtime;
        this.Status = Status;
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);

        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.UpdateAppointment);

        getDetails();
    }

    public FrmUpdateAppointment() {
    }

    private void getDetails() {
        txtAppointmentID.setText(AppointmentID);
        txtCarPlateNo.setText(CarPlateNo);
        txtAppointmentDetails.setText(AppointmentDetail);
        txtEndTime.setText(Endtime);
        txtStatus.setText(Status);
        txtStartTime.setText(AppointmentTime);
        txtAppointmentDate.setText(AppointmentDate);
        txtCustomerName.setText(CustomerName);
        txtCategoryName.setText(CategoryName);
        txtTechnicianName.setText(TechnicianName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAppointmentID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCarPlateNo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtAppointmentDetails = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JLabel();
        txtCategoryName = new javax.swing.JLabel();
        txtTechnicianName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("BACK");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 10, 40, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(650, 10, 110, 40);

        txtAppointmentID.setEditable(false);
        txtAppointmentID.setForeground(new java.awt.Color(153, 153, 153));
        txtAppointmentID.setText("AUTO-GENRATED");
        jPanel2.add(txtAppointmentID);
        txtAppointmentID.setBounds(190, 110, 240, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Customer Name");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 160, 130, 17);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Appointment ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 120, 110, 17);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("Car Plate No");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 280, 130, 17);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setText("Category Name");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 200, 110, 17);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Technician Name");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 240, 130, 17);
        jPanel2.add(txtCarPlateNo);
        txtCarPlateNo.setBounds(190, 270, 240, 40);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("Appointment Details");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 320, 150, 17);

        txtAppointmentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(txtAppointmentDetails);
        txtAppointmentDetails.setBounds(190, 310, 240, 40);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Status");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 480, 170, 17);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel24.setText("Appointment Date");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 360, 130, 17);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(640, 690, 120, 50);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel25.setText("Appointment Time");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 400, 130, 17);

        txtEndTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtEndTime.setText("jLabel1");
        jPanel2.add(txtEndTime);
        txtEndTime.setBounds(210, 440, 140, 17);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel26.setText("Appointment End Time");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 440, 170, 17);

        txtStatus.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtStatus.setText("jLabel1");
        jPanel2.add(txtStatus);
        txtStatus.setBounds(210, 480, 120, 17);

        txtStartTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtStartTime.setText("jLabel1");
        jPanel2.add(txtStartTime);
        txtStartTime.setBounds(210, 400, 130, 17);

        txtAppointmentDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAppointmentDate.setText("jLabel1");
        jPanel2.add(txtAppointmentDate);
        txtAppointmentDate.setBounds(210, 360, 130, 20);

        txtCustomerName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtCustomerName.setText("jLabel1");
        jPanel2.add(txtCustomerName);
        txtCustomerName.setBounds(210, 160, 200, 16);

        txtCategoryName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtCategoryName.setText("jLabel1");
        jPanel2.add(txtCategoryName);
        txtCategoryName.setBounds(210, 200, 180, 16);

        txtTechnicianName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTechnicianName.setText("jLabel1");
        jPanel2.add(txtTechnicianName);
        txtTechnicianName.setBounds(210, 240, 190, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new FrmViewAppointment().setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        String AppointmentID = txtAppointmentID.getText();
//        String CustomerName = txtCustomerName.getText();
//        String CategoryName = txtCategoryName.getText();
//        String TechnicianName = cmbTechnicianName.getSelectedItem().toString();
//        String CarPlateNo = txtCarPlateNo.getText().toUpperCase();
//        String AppointmentDetails = txtAppointmentDetails.getText();
//        String AppointmentDate = txtAppointmentDate.getSelectedDate();
//        String AppointmentHours = txtHours.getSelectedItem().toString();
//        String AppointmentMinutes = txtMinutes.getSelectedItem().toString();
        String plateNo = txtCarPlateNo.getText();
        String details = txtAppointmentDetails.getText();
//        Appointment Appointment = new Appointment(AppointmentID, CustomerName, CategoryName, TechnicianName, plateNo, details, AppointmentDate, AppointmentTime, Endtime, Status);
        try {
            if (!CarPlateNo.isEmpty() && !AppointmentDetail.isEmpty()) {
                ArrayList<String> ApppointmentDetails;
                ApppointmentDetails = new ArrayList<>();
                ApppointmentDetails.add(AppointmentID);
                ApppointmentDetails.add(CustomerName);
                ApppointmentDetails.add(CategoryName);
                ApppointmentDetails.add(TechnicianName);
                ApppointmentDetails.add(plateNo);
                ApppointmentDetails.add(details);
                ApppointmentDetails.add(AppointmentDate);
                ApppointmentDetails.add(AppointmentTime);
                ApppointmentDetails.add(Endtime);
                ApppointmentDetails.add(Status);
                Appointment appointment = new Appointment(ApppointmentDetails);
//                    appointment.Add();
                appointment.Update();
                JOptionPane.showMessageDialog(rootPane, "One appointment is updated", "Appointment Updated", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new FrmAppointment().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please make sure that you have entered all the fields!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtAppointmentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUpdateAppointment(AppointmentID, CustomerName, CategoryName, TechnicianName, CarPlateNo, AppointmentDetail, AppointmentDate, AppointmentTime, Endtime, Status).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentDetails;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtCarPlateNo;
    private javax.swing.JLabel txtCategoryName;
    private javax.swing.JLabel txtCustomerName;
    private javax.swing.JLabel txtEndTime;
    private javax.swing.JLabel txtStartTime;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTechnicianName;
    // End of variables declaration//GEN-END:variables
}
