/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import Config.Global;
import DataAccess.DataAccess;
import Classes.Constant;
import Email.MailUtil;
import Manager.MfrmDashboard;
import com.itextpdf.html2pdf.ConverterProperties;
import com.itextpdf.html2pdf.HtmlConverter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kianjun
 */
public class FrmViewPayment extends javax.swing.JFrame {
    DataAccess da = new DataAccess();
    ArrayList<String> data=null;

    /**
     * Creates new form frmViewPayment
     */
    public FrmViewPayment() {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);
        
        CurrentDateandTime();
        
        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.ViewPayment);
        
        lblRole.setText(Global.name);
        
        try {
            da.setFileName("Payment.txt");
            data = da.readAll();
            for (int i = 0; i < data.size(); i++) {//row
                String[] split = data.get(i).split("\\|");
                for (int j = 0; j <split.length; j++) { //col
                    jTable1.getModel().setValueAt(split[j], i, j);
            }
        }
        } catch (Exception e) {
        }
    }
    
    public void CurrentDateandTime(){
            Thread clock = new Thread() {
            public void run() {
                try {
                    for(;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " +day+"/"+(month+1)+"/"+year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: "+hour+":"+(minute)+":"+second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
            clock.start();
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1600, 750));
        jPanel2.setSize(new java.awt.Dimension(1600, 750));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Appointment ID", "Customer Name", "Category Name", "Category Price", "Appointment Date", "Appointment Time", "Product Name", "Product Price", "Quantity", "Date Added", "Total", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jTable1.setRowHeight(22);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.setShowGrid(true);
        jTable1.setSize(new java.awt.Dimension(400, 400));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 1570, 510);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 10, 560, 17);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(160, 30, 400, 50);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 0, 204));
        lblRole.setText("jLabel2");
        jPanel2.add(lblRole);
        lblRole.setBounds(10, 30, 200, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 210, 17);

        txtTime.setText("jLabel2");
        jPanel2.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        txtDate.setText("jLabel2");
        jPanel2.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("BACK");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 10, 40, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(1480, 10, 110, 40);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        jPanel2.add(txtSearch);
        txtSearch.setBounds(20, 90, 1570, 60);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(1470, 690, 120, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1600, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(Global.role.equals("MANAGER")) {
            new MfrmDashboard().setVisible(true);
        } else {
            new FrmPayment().setVisible(true);
        }
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        Display();
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            StringBuilder content = new StringBuilder();
            int row = jTable1.getSelectedRow();
            String PaymentID = jTable1.getValueAt(row, 0).toString();
            String AppointmentID = jTable1.getValueAt(row, 1).toString();
            String CustomerName = jTable1.getValueAt(row, 2).toString();
            String CategoryName = jTable1.getValueAt(row, 3).toString();
            String CategoryPrice = jTable1.getValueAt(row, 4).toString();
            String AppointmentDate = jTable1.getValueAt(row, 5).toString();
            String AppointmentTime = jTable1.getValueAt(row, 6).toString();
            String ProductName = jTable1.getValueAt(row, 7).toString();
            String ProductPrice = jTable1.getValueAt(row, 8).toString();
            String ProductQuantity = jTable1.getValueAt(row, 9).toString();
            String DateAdded = jTable1.getValueAt(row, 10).toString();
            String Total =  jTable1.getValueAt(row, 11).toString();
            
            content.append("<center><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAMAUExURQAAAK9BLnEeHCwrJRwkXFpPOBsiXCQdFR0lXAEBAUCPONQ0Lh0lW0iYOVhKQSNNJiRQJytkLjN3NEWUOC1pLyZWKu/EJxkubTuJN+7KJzY2NiFJJiZTKe2vKRgwci5sMDV8Ne6/KOuYKhYzdxM8hR1YohxSnBoqae/QKDFzMi0tLBYXFyRmqxdNlxU4fVtYWxRHkClfLRNCiyQkJTqDwwcHB+65KDQ3NkhLTR0lYShaLFBQVOmTK7OXWu2kKgcHB+ypKeufKmprbO6zKC9vMTV6uyptsTBztkJEREJDRSQlJRsmZSBfpjiCNiIjIyEnXhYXF+KKLOeOK+nMKikpKdaGLiQlJRUVFqZuM29xdBgYGCEiIklMTxwcHSoqKzo+PAsLDBwcHNS1RSIiIxkZGkGKxx4fH7FzNCYnJ9M0LtEvKkZHUeqXL0WPzEKRRDIzM9LDM76nY+udLEiW0FhZbOOSODMzNBoaGjMzNDmFR8aCPSAxVBAQEUmb1j1DPhAREWlrcN/JLMO7KzeCVxwdHTI2ayVNPhMUFOiXMi9qUTQ1NcirOiI9SQcHCCQkJR8fIOiRNFmXNlNWVOSPOLVxNurPMevLM+DKRt+RO9i5QDEvV8t7MCUtY+/QLBQUFAcHCIeIkDR5lOzOLSFakNuLPKp2MUyj2k5WT+7DKSlaTSxmYEpMTOGXRz5JP6eHMCxxiECLc+bQTsWKLzF4bz2Iix1DcOHFKe/TNStfP0BDcUut5b6wQI+JPUWSXTJ2pcR9O0hAU15/LyNPYPDVL9NLQNW8Jyhge0VuLniLNSkqKh1Qf01OY+vHKVpkX2lrLo5dP6RsRtM2LS1TMSkuZcyKM01OeWhgUiIjI42NmChQLTdaKaq0LVxHT/DXSeeHMH52SXBucTQ4aqWzaqycPuSaZZOnNk5OTnakMzVAanxSSDdaPYWhlqqaYOy3Kn+JYllqeL5KQEeNrjM1ZGmYq2KFgliLRc83L2SsxOKdVsCIUJB3ZH19fU9rQ9IyLLd5USAqVlXo2YQAAAEAdFJOUwBHEgf3BPgB9/f3zff3C/f39/f39/f39/f3Fff39/f39/f39/f39/f29w8h9/f3Hff39xr38PcsJff3OfcL9/f39xT39/f391ReQ/f39532Tff39zb3V+QXK3a5SouFoenROGLf99slys34beP393T3G+73W6zXw8f3R/fI97LVTPf39+3Z9/jN970o99zSqNj3sL73rZdqmEr49/Hg77Nj98L3hDX3geb396BojPf394D39/f3iNb3rff39/f3X/f39+qXXvf39+H3jdJx9vf34d/hc5346T/q9/f3v+z3mLn393/3x/f398r36vD39XD36/f399j3sffIg8HskffCv1tWAAAf1UlEQVR42u2dCVhTV77AMybXk1q8UK3RRFGDVTGpRk1JoiEIobZJVHbZwg4F5sGwFWSRAsqiLAKCCChS17riUve669R9G5eqbe0yXWY63WbpvDdv5n2f73/OzS5TAWnvmzf87Vdvlntyfve/n3sSOZwBGZABGZABGZABGZABGZABGZABGZD/U4LgD5sfT2mop58AQpqUolOnUijWOKiE1S0th9pFT8dCyXY1N+b45KRvZouEenebwtVVIb56KKHvekEpmxt9vH3FAoV3ThE75oUStnkFfvRRoKeXr6Clto9XM2Vzuo+vwP3ww4eHBV55NDsgrd6Bm4uKNjcGBnkprr6L+uJiRcvdXAFjX62Wrj3su1zDikqo1Z7NGgg29KnmQE9f4erw3s4ChW/O8VK4r9uXjeBU7j5xejaHJRDGPdGgXY2eroKNCb0zLyqlGdRxrsXkYFSrgCUQ7mo3U5xBVEpekJd43bu9IaGKGn18hedaNebHrYJGtkB8rAFz0J2PfBTnDvXcvDS70sGsbLRI7ROz5iPebZTtBXbzFW6s7eFUwttywMvBO2yui4KtqHXHtdnmElK1zeDyhx0dBSEKBDnwyfIYs7I+jTQbfdu47IAUfduosX1C2+bpKrQ4Cq6eaJmyTHcNRBelVokoc0WFapt9FO6H222ZUe06110sJcTabZ5b7O3+Trq3wP0QpqNoVdnWklsPxrg4uzg7u7i4jHhw6w87r0WpJBS2Qi+x+0b7HIrahTlbWCocNRt97tgbkubUR95iIKGUGMLZmSAQGTOG/P/BrZJrEUXpwPGw1mG0fYLlGrZq30PezeGO5tYIRrPxf1xGj7bBGGMR/Oh6IMC2ZDtc/fDDijzWyt+Eb9MdrYEJXkvfH23CwLMfYRV4cH2hl8D9WBntcGJCsPcu1sp4yUafzfbzQcrY91d5YhJnQsFMf7ZZ4Ph6INjVFyMeNN23q5gRFCgy9nqrQ962cQtRqq5bo0e/vyrIVbj0gssYM8MMi8yeDfoQBx+vGjOi6vaVCBtT0hx2ZSn4MvagcLP2EIjWAwbY1JhVga7CrPcxBUz+OVvB+gg+Pnly1Ygxi2dVrrfYF2oXsNWNMNfxqjW5I1XsA8Lh7DIGdCJYemE2gXjeRkAfiuDjI0eOrBoxomrWvI6jEabJa1p8l4ez2bS3itNTTBxRfxhNOLBvvL8q0Busy0QxzizXA32AYyyWutmz6ybPm1eZyzVlQ6/NrC4+pFx1/ZxcVO1WFzMHuPhsTAI6IQwvm+X6QuD4YsK0CRMmjD07Y0bVyMmT59V1aRF2dUVjCqvLKNQhMTYJJIl1MZkV9nHwjQtYJx9MwfOfYpIzwAFPnX1hGsjB546cBRObXDW7CUiy19nWn6xI9racUwhJS2zVgX3j+QtrIXZ9MAwTDCPCcMATZ18AObh9woSDRxZXQUT+HxnVqsjZwvbC2iHX5vAIi3tgdcwgrjHuwlrIJx8MM8uZhW4K4dIFcFQ9c+ZMQJk27exzYF91df6f3n/o3YZYBuHUbnP7/HEOcIwpF9a6gUuMHzYey4K3ccIfBUfDhl2ePh2jTDty5Cw4ysjJ875/vEJgpb26buVgzAo7OOMU4uDfEYwFuzHHygX4wfmp00FmHty+/eCEI2PHYpL3/kazzcFBW2w5LOogngEkguDfLViwYNRuMLOs4aNGwfH4TZOmTgWWy1OOgFYggI0Fkrvsg3C3OnfHgd1i/PiLELqWrBw16ngQ8zeWwvOTJhGU6uqZDAnopCONbdNC+gf/hINY1HEIXVkrgQc0M8ok5ydOJCjnd0y3IVGzS4IiuuMwY8Csdwf5umfhAuuLIYyM2j9/4kSCsgk7vYlk8rxKOascohIbP2c4pthyjBr+tqfCXaBw/2C4CWTInhfnz59PULCnEBLiJke5bIJgB+mWg8GAea9820fs7r50aMZwLEPK97wIQlAcSDpyWcztqgemcpfEXRu7snAMGbI70Efg/sX+/ZgkY8MrWAiKlWTaNMa4ZOxFrC4zx4h/ynE8yA2Hrh9e2QAkG14FYVDsSIhKZl1hSyVIeesxjin2HMMvQoXljfusExtOHjgwd+7cVxkWrBQTCWNcoJLbKpYiFzeWcRBTXTLO7CA2HCuhwgr+AEKXcOneuWaxJ2FUMoGohKWVRuUD28A7zqoQC8fw3Z7Qvq9ciUPXb+e+RIRBsViXnUrY8RKqy9laYDkalokjyFuQtXLoUFCM2P23L5nFQmKjEgwyi538nn3LzkGskdfCcREC1pLfDQW5iOvHv7yGxZGEqMRkW5UiNkB0zvaGNcVqWAwHcZAvhhI5DlVK1l9+BUJQ5h4AEmJcWCVm25rln8uCSqhYu0w4zsGwhg8f+jburIaaZDcOXa+//jpGeemlA8P3WlVitS3+URYisPyWY8SyVQhwgIMIsYMwsnJtEDj8G29glNdeOjA04+Sr9rYFpeO8Wbe1P7tKqFyX7kpei0IyjlscxESC3eTrtwAFSACEeInVtrCTzJvlH/UzR14OpT062qwQxrCOvGynkL9iB7HhGPqnr3GG/y9C8tqJoQfmMl7CxC2zk/Du0gj9TEpBSBO+5Ref5/25zlYh4448Wnxk+xEMYnYQV3AQqK9MHHvfeOubQCjpgQRUsnfogZMnT26wgJicZBb/z22ntqRoqJ8aBiFueNHmvOXpOV45ax6NtoasI4ud+Hwn/mKLRnAGOTaUVLwE5cTrb73z1n/jvMioZO+JEycObHjc29e87Z2T3ty2K4X+6VhAFbV38tJ9vFwV4nUbv+E51VlC1pHFfCy8xeNHjao+uKNwCMkgG/YUDjehnPjVG2+9885/4R7+67eIbe09uffAhv17HED8/b+5uk2scPXKad5cFP6TsCA6ZdfyHFdf8bbDD/clZGvu8niLzZZVxXDw+Yu3V58dO2HaCzvAQZb8MP/FF8sJR8bwA69jkHcYN8EgUEBuOLAhwwFkFp9/N7y2/dDGdWJf75zlm7fQ/Y2CqIS2dFeF8NzDfe3ZGrhS9FEAMbt6lZMJZNa8ySMxyE1o1b+ZOB9INuwdnrH3TwdeY0De+QZi8DGIwK+9NBfr5HEQ3lEEqtcmvLv6sNjVJz2vqH+XVzQJeTm+gnUtrdnm+lRUyeM/GmNy9SMOIO8Fegmy9mCQV145mbHhpZde+9XrbxCSt/4bF10kJ+7de4KYlr2z8yqZ7S2I0rSvvvqtt09zP6Kg8DbAOLxvi83dqYjbMO86U+y1gPAJyO9J5N0/cSJoBEAOYBAgeQuT/GWhtxCKLihSXj2ZsWdDebl9+OXzOrRWK8hub9nmmt4W3l/29YvlroKHrdl29/zud/jz+E5VDEgd3xZk7CqIvN8VFm4iIK+e3DCXqATrBORrXKr8idSNG6BpzNhklxD5PP8Iu/DS3uLrs7x/FrjRlnTXbcyWKpsn78/C864jlvXcIzsQbFjHNp3P2E9AXnl1LgZhSEBeJzGY1L97yzOGl++3lCgEhO+vtv94unWbT2O/rAynLHcVtnIdRkJl/njeTlU4iVTxLCCzJo/EhpV1fvrU/Rn79+/BKjGTAAqWv0AMdv8aK2TvyYyMPZvs0gifP9ixSKEStvn0y225zW7ih49tP0K5/kziwCCL+VaQeR3EsGZOnzq1fMiQjP2MSkwkWP504jgxLlKg7CkvJ5ZlC7L+sRkccg3qh1vwVLOPYPVjmjWB8J3qIIs42YJ8BYb12Qszp4NKcFdSuIGoBLe5pK2CKmsoXn38ramK32TXWPH4vMdB0D5FUFs/uAho5Nxjm/woAgLu/uj55xdbLctp8WlsWL9/AUimnifLQeWvWEiInMB1sKc4+AdrX2Wt4rFGyhwnULvO17MfNIJkELMOtzts7DX5CEz9SJ1VIVCi7PZ0DX4PUiJWSSFRyYsmEoKy90QGbnwDvYRZJx9ffICg5egjCCU8FHo39sumiKJ0b8G51Qlc27iF7ptAeE5WffD5jz6GWvGD6oPTGJWMYtZ6MQlBmbvXpl38LSkYz5fbLAcBB88+alHZ+84JfdP7Zy8BKmr0UrgDiu0++PsduNolyrBxkTVr3cTBK4dA4UhUcj4D2xaOwRjl1QMnhlvaRU9F8A/zN+2ZVL7DXiG2eYTS1O477C7wTf9FP2VEKiUPbzM+t3FfAs0x7YGT3bZRhJnI/yYY1sfjsUExxrV/FFEJRoHuw9qcZFyEGJy1t7x86o7CmZYl08WgXVNmR3jnamvLOqEA8mFR/zXy9CkofBXA8rA1IZuLN/ThWstReB/iiOXfgX1jx47LOy5PnbqpvHBIOeTFF/dkZGRYQE6cfPEmNFlfbNo09XI5WcQ+u3379qrnquoe4VoLup7sBKBwFyqgbtwc3p8VMBV+Z3kONCICofvhltYt2Rr66GAbAiceVgoYlmLJGkgl1VgRo4YUAsmkSZtI9bh/uLXJGlo+f/6mtW6C4O/xrcTqwurtB6dMeXnc8889N7uKf1STvQUgzrkLxb5ebo2bU6h+ruSp8FN56W4My7nDLfv+vsZp8GAeqAXbA9GO0w0o3j/m86BMOUgC1pDC8+ehlJoE1eP8PYTCpBF80+p78Pdj08svv7ADOv2XGZAZMy68903L4XPu7kIBVkbern7HYKrRlF15jTnkOxJCd/fgrGPH3/vw9Bp//uDBg8FHeKcXQo21hsfDtXy1+f7UDoZk4sT9Vo2Uk/tVNz3F7t+dvwwOcvbl7duHnTlz8YulWcFCoUCs8HWFrqqtPfyna90pOjxhc3M6hlGIBQJhcPCSrKWfHf/4PeBZswoM67STqSs5y+hkSGHh+ambNmGUcotl4Yp30qTzUNBnfX95x18//vizY1lLlgQzBF5ubp6Nebu2hHN/2vUHhKDnLdqc1+jm5uPl7eqrUAAPAyQWuGcBE2jp9O9Bqocztw3Lp5cXbsK+Uo7jLpa/fv/9D999990xsbt7VtYSsxK8fAAhKLAx704RGNTPsyYEYWVQwt9vrFq7MNAT82AgrCAhWBxIMMgSLFlZWUuXLj12DP4DgUmD4BeFRAQwf6IDhiBw7aqbX334iYj7M39tjFrv7/RozekPCU6QJ1YQaAjEF0RBRGwn+Bn8Gn6Pt7eXF56/mycmWLh21Y2vrl+o84e4wcIqtrwSp0Eez8l/DfDcBJaFa4EpMCjI0xO4uhFPLEFY8ORBAauCvHyPnblw4YgTr+65GXVQg97WsnDD6iguf825fZWn75LTgLTm9OkPP/zqq69u3Lhx8+bNVaveJkL+3g1P7N59/PjFixffW/nXg5AGqxe6ui85A5G3qg7nEIjjbKzGc3Kha+cxLDinC49bUqSTkxMTu0Yycbhw2mVI64WXZ+7AQQuCV+GQwoMTJpwdfxFC8AdMLpwxe8wjPiv3R5Cs0lr1QujNWuNQtJhIIA5XHyzEq3QZhRkYo3xH4Y6zOw6OrV6wYMHb3sLgM+Oeh1w4e8SYqkfs3GqnrvibS5SvSE4ntSPWkekASBiUgxPOwsyrq88e3AGCN2dClQgg44edCVK4Lx1HOEaMcam6wso9RBRx26Z6z3Iy2xnfemBCgVlPsJWxeLvZdryZbspuH0HwGXAQUIiLyy2WbrRTd3mMl9wI8g5+bzC/G5llQhk51k5Gbq8eRjimXIAqeOnzMwiHSxdb+2qyiUqc1ix0E3/mz+9eAAVYCIxVqkctYDheHrcbWrEzYFjAcUvJ1p4tlOaPu2yoeoNP84hr8HgmH7E5mIVZMIxFti9gOF6GeHUBSq6lM/A3S5y72NseRNqrNQt9xJ8NhpjLN/1xOGD0gmFMMms75iCVO8TdG54K94uYgz2F4MWUDr4/VsiH/J7ILADCseCIyawwx4z314JK8FexMtnci03f5YFCBJ85mTMjvwcHvO3YrMYxHLNHXA/ydT/j7PwHLYscOCuCQpac5pmWIJz4PTmos6gDf8nn/bU+gqVjHkSxvDuzDCvEn98reXSEwSBpcIzL9UDX4DNbWd7kz/kcV4u8ntsVk/qrCAZJ5y4uoBLhVQnLHHSjj+AYj99beTSbwcAczqNvQKGSwi4HOuXpu67Jv9cgTlVmjKrRo0ePgcB1iF3T0jR7CQ6pPu01CK+O+XalcxWU/HV/+Jun4iqrX7FCRemKdbVI9ak/v1dhi89fTL4y6jz6EZ/vfzRiy0fewnfZjFqozUu4GmxCdrS31vVotItzXV0d5vhUhqhmT/FGDYsg4aCQBHwltXf9SUTimcLSkw8WgzZwI9lxF2//a//IdV0Cm67uJWhhLqQkrYOJrmYneMIBz2nxI3zQcY1sNQtvdhOw6O7cPF/3VpNpU1GVvXd5fqVpQzz1eZDicDhrXqJKF5+zfC0dqY52dFP7/sgBuLnK/HME2djdWbOsXT7CFpuHdG5lb7TBq0yz2fyT5yZoYcu26GZvd7ugScmu3MYzxLdL+E848L99RWY78VNBvutYsi2Uku571b6yQFxl05qeFCy8jrtq+1sfKWBb7SyBnMoRtzjsQaLaty38e6X/YP4/T4hA4V/58dttDnecaRy32Fl8oPO8HNMx9e42r+ZsVe6nt/15NndJbW4AO4FNfZqruvOtT57Drz7cCVJsZOdLfIMaXYX2P6WhubPNOy+c/JaI/mhlh33dQlTRUXlUr6IpxH13m+vyBDuSBMiJ7Px2UG267zq7siJ8tdgrb5A5x8jK0u5+Wvnnjg5/Ih23Kz+9m1amMt3gBt352t93zm70PlfLCkhCDtRHNj+5k7BRkdM2yPZ2EKJomTpKl7s+VxellHHt7kOh9nWKnF2DrE9o8nyC2alS2n0Eqy2XFGnAWNJ3dV/4dRuMqISrYu+8bMsI3DY3QTs7JbyXcJ9lGimHFF7Le7dlBGWvFrgut2zXoXZ5itmJvwk+5joP0e1XXXPaet0acVuv+ua0me6lYxB2ipTaHAXxEUQltHzrk36qD7GT2tIi9l5+inga9TlLpsWRLPcWtGppUfvqba74uvbJPgdhpTTvktHclOXeLDk7dcfTW7yx5eq33jnN7X3daoGoWrgOPo1/+1ujl3gjO3mEE54X5Obj45aeV/RUvx2nART8C5yCc6y17eF38vLadm152sICcVNaV2+8urGVvRYRUahfNr6YfqiOMyADMiADMiD/HwUxXVIvEwayabAs0ttz7Z5CT7lBUBQQiiUgQNqbYShDIhbmTEYMSpWkR0NIDKHkXJvffOEayEiGp1lnkVzp9MDSIO2VQqIueThIXFxSfqa8Byh0WgW8fdlOke11SYanwvRPU8VomuY8gyW5VzsTkDYVnzZnmUWYUUoNTx4FRYThU3W275QvgvPjnmb7EJW2jMzgmTnG3nzZHImK8Un5UWVmueaHp/fMiidbKAPyTMDjINKn8PQyPGhFJyaJof958QhlX3cgb9p4BZVLLkgmcjzV0Yl/ChCkTIYhw3SJcfCXR0z3vkb/8dcgp7oHsXlKTawr0m7W4fjUX2/5yUFERjh/TiZFxeBJeHTvbOH/+R8gv+4WRCUzi0qXip+JC7F7W8pv8Ll//KlBuNGYww8UIarBJGEhqHcgHklmCYvzwCPEZXKfDCLrbxBuogcMmKrCVqxOwoPHdxc3fgTkmTkmYR7EGUPtrbN3ICv6CIICsGcsy2Ty2U4STo2yXoEkNTU1xYJEg2QmGuSObaAJ5HP7ACBbgT8q93EQeR8dvZRcRnNCYy6q3+OhK/yXvwHp3kdEEhoLF6Q7q0Thz+Jz7UE4cgKy1Q4EG0QfQSRGPFzxmxZhrD7zsRkhMleNQ0LMd4xa3V+tbs7lSMgn1Sspc5GHJJH4Opb2aQ+RxI84uohrERWZW5yuJ3UCZHYC0qclFpSJpz0nKcagjgBRhaQZPcg17EtiR1vxufW2d8iQ8h6e3L0oqscgxr7tw6JjGEP26Lx36dK9MBLvnvGI7sNgSKSPI3ZqF2ToK8ThL5U9eUSkisfvze/bl1MR1xBdTOI1E/HmeMSV+un68m0lKiDaD0uM3M77Y/yYZ0OePEAiGSBa39fCm6KVBn1kDA53MZF6g1LSx3Uvs1/YnU2Zn6V6PsBTrf+ZPvDfd/EO/QvJj4KE/+JfR370x8CLnn322V+SP47yyx+RZ1mRP/6Yn1KD/nWE/rdyeYvrWx/auJfV2WzeaXlsftFymvVN5mEsr5Myynym9UTLOaYju40GyOZznyBRerIOIwoJDVBKoBHR4YdKvdJcg+n0ep1BCQmC1umIgrnK0FCDnMsR6dVIBK+mpaUptfoo8xjMv84Hb+ZCStWrkEqPf9chBM5V61XkaQ48RUXp8Zl6jlyPx5dRUE/C2SEiCj5bJcGDpqWFqvQ6CYdLznlySq25V4Z7gvykgvowowjFXIqAy5XZaa6qtakVpaWlYdDpKS/VR5DqMmxRQVJpFHSoMZQq+d4ikFDZvSaEQorxGKmElq4pEHGQoUKH9J0wIupK1aK0ZWq65BL0bbmduZqSTnzilxxlGIyQXBqA6NikRYuS8kOQviJXnl8a1plUmq8sqSijVPfSelLtqSsqYmkOCu1ME6n0MRQGgcnm36s3ra1J6gukUqWxVE5trejEP9oZ2ZmmEkV0iZA0LhJJV/hJpVKVVlYRi+Sl+WqZVK8n53GNAMIxxBmQfg5eWYqJ16LEZ0JQWWcaxc2vpzU1SUo4UcWRxu1USdUVDUjp0SWTR8WKkH5ZLlcqTfRIk0Zw1SuMcmNDT6pHibGkq1ONUIBHmNEvMgQRECotXhcXSZlALm3deiXpTYkqeWvBPS2Hmx+Lt/yAKUg9MEh9U9MVDQeDhC4ro8gr9iChFVvjjDITCIdqKJYb4nRIU9PZ1FQCZiiNKwkN3doZA0PFGf1iDFwMAtciwGM99hd93KLkHnW8hgp9VGcDF/p1Y/I9j2IpikmOgC4pVhlvamsk+Z31qUa/ECrtUtQ1j0yKjo/GtkMhM0hs7E4uAUlcdp/sjHDQSGiYOjOuIdYEwtF5BMTmyzkAUhJbIscg91LDOiNFHG5AQ/y9ZSsMGIRjBuFw/eJCe+LrVENScXFSXAiSRNGUNgY+F/tIaFxxcbwHY5mS+hoN+X21+uL81LB4GfJLgqsmuRZiAonmIig1MYgyzk+GuGpm3QT51as4lH6FEunD1NzMZZ1mEG1qcmciBSCXtLRWK8GmRek64SRulAhp9R5p9iBoa1KPfppdHaaTSEKS/CS6pBq/2GSjBINojdESicgYT/4BFy2A4AH1yUqJRO+xlVLlw1tTkzKRCnxEVRpNcGUVOxE3c0WqX01yvIqAJMbV+Pklv0kjPcyE7iIgc0JIO5gEugKNfAnSxFECCDc6LApJk1Njd6YWK00gut6BGCJFCFGZkSLaEBkdGSrnoIBIlTxSCbE8IJL8HI4okvl+WmgijZAoMpJGooDMmEQpBa8YOPLIUIp5VyioVxkZE2kQmVucyJiYRBkE3kgpNJCZkRKOIRpbuyoSFIIbGJCuK8wISniOq07EJyB4G+5/1NEMgCGyZ4tC1sxmyYjmOy/IPmHapTnmb9skaZdV7RKpNZkiDsc+dyKufb5k/nU4ZJ+o+/MOVr/fEuv/8Sm5VA6aFkE2kOLFuGwVHETAszg7QC+vkkKulUgRhyul4V0Uh5JKoMeWZkPAQVIm11CiCHJAy1RyGsmx1ZHHcGjKAFw4kJNBuOR1+BsyuVQqQTA2ZDG5COHxteTDaQm8A0mk+GRKKkLk45/YoUbmF6RGy1FXaU1NzRV4oiu/uDS/RhsdD48DkMFYY0yNQro3JRCSQ9DWFaGUqGA9EvmlFqRGcrUFMdhBJJnwKFqElA0FNcYuOi1eyfUjfmUoKGlg7jPIi3VU7IooKiJfyd1ZGkXJUpUcWUNqgTERqZNzkbYgl4oqvUYZjPkr8gvu56bKUIgRXjVQovwCGQrNf2LtixLrQ2h5TQO1M1WtluG4SdOfpNI08mtSq7WUslRH0wY5J6BUqQwpDUGf3EsKFS1aT/mVyGh1cqJ2EQ5Z3Mz6CFpVEEMbYyS0PISiYo2RDWQ/f2KJukCJb3wh+YoAamdYmE4ar6abkpJCtMlK2rhTRueGGWi/Bq6+nkaxiwpEXLpsRYiEWp8skcWnSSTXkpSi0jCjMjT+yV8j9esCY1lfT+/0SE5m7n2hT1JxFuhMhqIoIJmpAAM8Ll261GmgPvmyK0m3aL2kOApx6NgGE0gDjIGuFctL1Zp//OMfNFImMxETZS4qqY8tocwgDbFh6+sBJDo6vixZKo+HN4kKIqmo5JB8KNoKou7pOZz7kHgwSNklqF9lyXpRaWa8MfHJICiyIIKSxRpBIyKRKW5iEI5fk1wl4YYk6bi0Wo0CStURaqyRL+mYior13IadMkq9KBJAuBRFx6RGcGUlfpL8TO21T+LB4mP8SE6kk9Si+GTCRED8JNEVYRiEbriXpOQau7TcqKRQRDUUxEfQsfUll/IlyAyiStbRXF1SiKhUH5G6ogcakTSkxta8qeRcKTCvBKFPCjBIfYNf03puZHxJSWompSuWIFExBuFIYivWc5TxBU2pfnJtQXGDX0mUrKGgqcCoQobiptgSMGcUzYBQxprY1OSd2FvkpQYAoehYANkZg+QlSUpkiP+yKR7Xq7rOGEq5SC2Pqs+l7pdikHotFQqfHJ9IieJ1VERyfQ++oUwrDSEQHdTWdVE17ixC9DodtBuU1BAip5AsigsNhgjhl7Q444lCcIcCPQW8S4XwGOAUSG6AfgL+Ng8mMgTIVOReEa1TIdAsR6YTUWo1NA06iIjyEIMUE2t1co4sCvJyiJrCoyOVDgcygwGHNziRo+zZ8vNjTZhd32b/P5v8ZrdBwtriOeyCsMlu1hzq2IZaRka2Sda2C+UMyIAMyIAMyIAMyIAMyIAMyIAMyIAMyL+E/C8W8VT903d3IgAAAABJRU5ErkJggg==\"/></center>");
            content.append("<center><h1>APU Automotive Service Centre Receipts</h1></center>");
            content.append("<center><h2>Asia Pacific University of Technology and Innovation<br></h2></center>");
            content.append("<center><h4>Technology Park Malaysia.<br></h4></center>");
            content.append("<center><h4>57000 Bukit Jalil, Malaysia.<br></h4></center>");
            content.append("<p><b>Payment ID: </b>").append(PaymentID).append("</p>");
            content.append("<p><b>Appointment ID: </b>").append(AppointmentID).append("</p>");
            content.append("<p><b>Member Name: </b>").append(CustomerName).append("</p>");
            content.append("<p><b>Category Name: </b>").append(CategoryName).append("</p>");
            content.append("<p><b>Category Price: </b>").append(CategoryPrice).append("</p>");
            content.append("<p><b>Appointment Date: </b>").append(AppointmentDate).append("</p>");
            content.append("<p><b>Appointment Time: </b>").append(AppointmentTime).append("</p>");
            content.append("<p><b>Product Name: </b>").append(ProductName).append("</p>");
            content.append("<p><b>Product Price: </b>").append(ProductPrice).append("</p>");
            content.append("<p><b>Product Quantity: </b>").append(ProductQuantity).append("</p>");
            content.append("<p><b>Date Added: </b>").append(DateAdded).append("</p>");
            content.append("<p><b>Total: </b>").append(Total).append("</p>");
            content.append("<br>");
            content.append("<p><b>Generated Date: </b>").append(new Date().toString()).append("</p>");
            content.append("<br>");
            content.append("<p><b>--------------------------------------------------Have a nice day--------------------------------------------------</b></p>");
            InputStream htmlSource = new ByteArrayInputStream(content.toString().getBytes(StandardCharsets.UTF_8));

            File pdfDest = new File(System.getProperty("user.dir") + "/receipt.pdf");
            ConverterProperties converterProperties = new ConverterProperties();
            
            try {
                HtmlConverter.convertToPdf(htmlSource, new FileOutputStream(pdfDest), converterProperties);
                JOptionPane.showMessageDialog(rootPane, "A new pdf file is generated.");
                
                int confirm = JOptionPane.showConfirmDialog(rootPane, "You want to sent E-receipt?", "E-Receipt", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    MailUtil.sendReceipt(getCustomerEmail(CustomerName));
                }
                
            } catch (IOException e) {
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Something happen. Please try to launch the system again");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    void Display() {
        jTable1.setModel(new DefaultTableModel(null, new String[]{"Payment ID", "Appointment ID", "Customer Name", "Category Name", "Category Price", "Appointment Date", "Appointment Time", "Product Name", "Product Price", "Product Quantity", "Date Added", "Total", "Status"}));
        da.setFileName("Payment.txt");
        int row = 0;
        data = da.readAll();
        for (int i = 0; i < data.size(); i++) {//row
            String[] split = data.get(i).split("\\|");
            if (split[2].contains(txtSearch.getText().toUpperCase())) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new String[]{"", "", "", "", "", "", "", "", "", "", "", "", ""});
                for (int j = 0; j < split.length; j++) {//col
                    jTable1.getModel().setValueAt(split[j], row, j);
                }
                row++;
            }
        }
    }
    
    private String getCustomerEmail(String CustomerName) {
        String email = null;
        DataAccess da = new DataAccess();
        da.setFileName("Customer.txt");
        ArrayList<String> data = da.readAll();
        for(String rec: data) {
            String[] split = rec.split("\\|");
            if(split[2].equals(CustomerName)) {
                email = split[5];
            }
        }
        return email;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViewPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
