/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technician;

import Classes.Account;
import Classes.Constant;
import Classes.Technician;
import Classes.User;
import Config.Global;
import DataAccess.DataAccess;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oodjassignment.FrmLogin;

/**
 *
 * @author kianjun
 */
public class PROFILE extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    ArrayList<String> data = null;
    /**
     * Creates new form PROFILE
     */
    public PROFILE() throws ParseException {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();

        jLabel1.setText(con.LoginAs);
        jLabel2.setText(con.SystemName);
        jLabel14.setText(con.Profile);
        lblRole.setText(Global.name);
        jLabel20.setText(Global.role);
        jLabel12.setText(con.Security);
        jLabel24.setText(con.Question);
        jLabel25.setText(con.Answer);


        getDetails(Global.login_id);
    }
    
    private void getDetails(String UserID) throws ParseException {
        da.setFileName("user.txt");
        data = da.readAll();
        for (String rec : data) {
            String[] split = rec.split("\\|");
            if (split[0].equals(UserID)) {
                txtUserID.setText(split[0]);
                txtUsername.setText(split[1]);
                txtPassword.setText(split[3]);
                txtRole.setText(split[4]);
                txtQuestion.setText(split[5]);
                txtAnswer.setText(split[6]);
                jLabel15.setText(split[7]);
                Date date1;
                try {
                    date1 = new SimpleDateFormat("dd/MM/yyyy").parse(split[2]);
                    LocalDate localDate = date1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    Calendar cal = Calendar.getInstance();
                    cal.set(localDate.getYear(), localDate.getMonthValue(), localDate.getDayOfMonth());
                    txtDOB.setDate(cal);
                } catch (ParseException ex) {
                    Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
                }
                    

            }
        }
    }
    
    private void CurrentDateandTime() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " + day + "/" + (month + 1) + "/" + year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: " + hour + ":" + (minute) + ":" + second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
        clock.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        txtRole = new javax.swing.JLabel();
        txtDOB = new org.gui.JCalendarCombo();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtQuestion = new javax.swing.JTextField();
        btnActivate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1020, 750));
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 17);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 720, 110, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(140, 720, 100, 16);

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 255, 0));
        lblRole.setText("jLabel2");
        jPanel1.add(lblRole);
        lblRole.setBounds(10, 40, 200, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Category");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 170, 130, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage Product");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Customer");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 270, 130, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Appointment");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 320, 150, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Manage Payment");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 370, 120, 30);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel5.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("PROFILE");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16);
        jLabel16.setBounds(100, 10, 60, 20);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 650, 250, 50);

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(140, 10, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 750);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 0, 0);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 500, 150, 0);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 30, 400, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("LOGOUT");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(30, 10, 70, 19);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, 10, 120, 40);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel19.setText("User ID");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 120, 110, 17);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Username");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 160, 80, 17);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("Date of Birth");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 200, 90, 17);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("Password");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 240, 150, 17);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Role");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 280, 150, 17);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel12.setText("jLabel4");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 430, 400, 60);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel24.setText("jLabel16");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 510, 150, 17);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel25.setText("jLabel15");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 550, 150, 17);

        txtAnswer.setEditable(false);
        txtAnswer.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtAnswer);
        txtAnswer.setBounds(180, 540, 300, 40);

        txtRole.setText("jLabel20");
        jPanel2.add(txtRole);
        txtRole.setBounds(190, 280, 290, 30);
        jPanel2.add(txtDOB);
        txtDOB.setBounds(190, 200, 290, 26);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(180, 230, 300, 40);

        txtUsername.setEditable(false);
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernametxtUserIDFocusLost(evt);
            }
        });
        jPanel2.add(txtUsername);
        txtUsername.setBounds(180, 150, 300, 40);

        txtUserID.setEditable(false);
        txtUserID.setForeground(new java.awt.Color(153, 153, 153));
        txtUserID.setText("AUTO-GENRATED");
        jPanel2.add(txtUserID);
        txtUserID.setBounds(180, 110, 300, 40);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel26.setText("Status");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(500, 120, 110, 17);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("ACTIVE");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(630, 120, 70, 17);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(640, 690, 120, 50);

        txtQuestion.setEditable(false);
        txtQuestion.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtQuestion);
        txtQuestion.setBounds(180, 500, 300, 40);

        btnActivate.setBackground(java.awt.Color.green);
        btnActivate.setText("ACTIVATE");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateActionPerformed(evt);
            }
        });
        jPanel2.add(btnActivate);
        btnActivate.setBounds(10, 690, 140, 50);

        btnDeactivate.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        btnDeactivate.setText("DEACTIVATE");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeactivate);
        btnDeactivate.setBounds(160, 690, 140, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        FrmCategory frmCategory = new FrmCategory();
        frmCategory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new FrmProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new FrmCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new FrmAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new FrmPayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        try {
            int confirmed = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Account Logout", JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION) {
                Account account = new Account();
                account.logout(Global.user_login_id);
                frmLogin.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid logged out. Please launch the program from login page.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void txtUsernametxtUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernametxtUserIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernametxtUserIDFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();
        String Status = jLabel15.getText();

        ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add(Status);
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
//        user.Update();

        try {
            new PROFILE().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();

        ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add("ACTIVE");
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, "ACTIVE");
//        user.Update();

        try {
            new PROFILE().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnActivateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        String UserID = txtUserID.getText();
        String Username = txtUsername.getText();
        String DOB = txtDOB.getSelectedDate();
        String Password = txtPassword.getText();
        String Role = txtRole.getText();
        String Question = txtQuestion.getText();
        String Answer = txtAnswer.getText();
//
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, "INACTIVE");
//        user.Update();
ArrayList<String> TechnicianDetails;
        TechnicianDetails = new ArrayList<>();
        TechnicianDetails.add(UserID);
        TechnicianDetails.add(Username);
        TechnicianDetails.add(DOB);
        TechnicianDetails.add(Password);
        TechnicianDetails.add(Role);
        TechnicianDetails.add(Question);
        TechnicianDetails.add(Answer);
        TechnicianDetails.add("INACTIVE");
        
        User userTechnician = new Technician(TechnicianDetails);
//        User user = new Technician(UserID, Username, DOB, Password, Role, Question, Answer, Status);
        userTechnician.Update();

        try {
            new PROFILE().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {
            // TODO add your handling code here:
            new PROFILE().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PROFILE().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(PROFILE.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivate;
    public javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblRole;
    public javax.swing.JTextField txtAnswer;
    public org.gui.JCalendarCombo txtDOB;
    private javax.swing.JLabel txtDate;
    public javax.swing.JTextField txtPassword;
    public javax.swing.JTextField txtQuestion;
    public javax.swing.JLabel txtRole;
    private javax.swing.JLabel txtTime;
    public javax.swing.JTextField txtUserID;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
