/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import Administrator.FrmAddUser;
import Administrator.AfrmDashboard;
import Config.Global;
import Classes.Account;
import Classes.Constant;
import Classes.User;
import Manager.MfrmDashboard;
import Technician.TfrmDashboard;
import com.sun.glass.events.KeyEvent;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author kianjun
 */
public class FrmLogin extends javax.swing.JFrame {

    
    /**
     * Creates new form frmLogin
     */
    public FrmLogin() {
        Constant con = new Constant();
        initComponents();
        this.setLocationRelativeTo(null);
        CurrentDateandTime();
        
        lblSystemName.setText(con.SystemName);
        jLabel6.setText(con.Username);
        jLabel4.setText(con.Password);
        lblUsername.setText("");
        lblPassword.setText("");
    }
    
    public void CurrentDateandTime(){
            Thread clock = new Thread() {
            public void run() {
                try {
                    for(;;) {
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        txtDate.setText("Date: " +day+"/"+(month+1)+"/"+year);
                        int hour = cal.get(Calendar.HOUR);
                        int minute = cal.get(Calendar.MINUTE);
                        int second = cal.get(Calendar.SECOND);
                        txtTime.setText("Time: "+hour+":"+(minute)+":"+second);
                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.getCause();
                }
            }
        };
            clock.start();
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSystemName = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        chkPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        lblSystemName.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lblSystemName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblSystemName);
        lblSystemName.setBounds(30, 70, 970, 70);

        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("jLabel2");
        jPanel1.add(txtDate);
        txtDate.setBounds(10, 690, 190, 16);

        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("jLabel2");
        jPanel1.add(txtTime);
        txtTime.setBounds(10, 720, 200, 16);

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login to your account");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 10, 320, 40);

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsername);
        txtUsername.setBounds(20, 90, 450, 60);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 200, 140, 20);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel4.add(txtPassword);
        txtPassword.setBounds(20, 230, 450, 60);

        chkPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkPassword.setText("View Password");
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        jPanel4.add(chkPassword);
        chkPassword.setBounds(20, 330, 140, 23);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 60, 140, 20);

        lblUsername.setText("jLabel7");
        jPanel4.add(lblUsername);
        lblUsername.setBounds(30, 160, 280, 16);

        lblPassword.setText("jLabel1");
        jPanel4.add(lblPassword);
        lblPassword.setBounds(30, 300, 250, 16);

        btnLogin.setBackground(new java.awt.Color(102, 255, 51));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin);
        btnLogin.setBounds(20, 380, 450, 60);

        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Forget your password ?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1);
        jLabel1.setBounds(180, 450, 160, 16);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(490, 160, 500, 490);

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.setForeground(new java.awt.Color(255, 51, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("QUIT");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(40, 10, 40, 19);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(880, 10, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AASC logo.PNG"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 160, 445, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        // TODO add your handling code here:
        if (chkPassword.isSelected()) { 
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            if(txtPassword.getText().trim().isEmpty()&&txtUsername.getText().trim().isEmpty()){
                lblUsername.setText("The username is empty.");
                lblPassword.setText("The password is empty.");
            } else if (txtPassword.getText().trim().isEmpty()) {
                lblPassword.setText("The password is empty.");
            } else if (txtUsername.getText().trim().isEmpty()) {
                lblUsername.setText("The username is empty.");
            }
            else {
                String uname = txtUsername.getText().toLowerCase();
                String pwd = new String(txtPassword.getPassword());
                
                User.username = uname;
                User.password = pwd;
                Account account = new Account();
                if(account.Login()) {
                    if(Global.role.equals("ADMIN")) {
                        AfrmDashboard frmDashboard = new AfrmDashboard();
                        frmDashboard.setVisible(true);
                        this.dispose();
                    } else if(Global.role.equals("TECHNICIAN")) {
                        TfrmDashboard frmDashboard = new TfrmDashboard();
                        frmDashboard.setVisible(true);
                        this.dispose();
                    } else {
                        MfrmDashboard frmDashboard = new MfrmDashboard();
                        frmDashboard.setVisible(true);
                        this.dispose();
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "The username or password is wrong, Please try again!", "Login Failed", JOptionPane.ERROR_MESSAGE);
                    lblPassword.setText("");
                    lblPassword.setText("");
                }
            }
            } catch (Exception e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new FrmForgetPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)) || (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSystemName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel txtDate;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel txtTime;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
